import test from 'node:test';
import assert from 'node:assert/strict';
import { createServer } from 'node:http';
import { mkdtemp, rm } from 'node:fs/promises';
import { join, resolve, dirname, basename } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID, randomBytes } from 'node:crypto';
import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import FinalLab from '../src/FinalLab.tsx';
import { finalLabTitles, specification, validateSpecification, evaluationDataset, evaluateDataset, runFinalSuite, makeReport, validateUpload } from '../src/capstoneRules.ts';
import { finalLessons } from '../src/finalLessons.ts';
import { WorkspaceStore, WorkspaceError } from './capstoneStore.ts';
import { ResearchRunner, type ResearchApi } from './capstoneRunner.ts';
import { CapstoneApplication, capstoneOrigin } from './capstoneRoutes.ts';
import { signFixture } from './operationsService.ts';
const password = 'Course-test-password-123';
function setup(file = ':memory:') { const store = new WorkspaceStore(file); const alice = store.register('alice@example.test', password), bob = store.register('bob@example.test', password); const workspace = store.createWorkspace(alice.user.id, 'Release research'); const document = store.upload(alice.user.id, workspace.id, 'release.md', 'Search supports date filtering. Existing queries continue to work.'); const investigation = store.createInvestigation(alice.user.id, workspace.id, 'What changed?'); return { store, alice, bob, workspace, document, investigation }; }
for (let lab = 51; lab <= 56; lab++) {
  test(`Lab ${lab}: rules, six narrated snippets and renderable page`, () => { assert.equal(finalLessons[lab].length, 6); assert.ok(runFinalSuite(lab).every(row => row.passed)); const html = renderToStaticMarkup(createElement(FinalLab, { lab: lab as keyof typeof finalLabTitles, active: false })); assert.ok(html.includes(finalLabTitles[lab])); assert.ok(html.includes('Export evidence and notes')); });
}
test('AC-01: persisted accounts, documents and investigations survive reopen; unfinished work becomes unknown', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'agents-capstone-test-')); const file = join(directory, 'workspace.sqlite');
  try { const value = setup(file); const operation = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'What changed?', 'fixture').operation; value.store.close(); const reopened = new WorkspaceStore(file); assert.equal(reopened.identity(value.alice.token).email, 'alice@example.test'); assert.equal(reopened.documents(value.alice.user.id, value.workspace.id).length, 1); assert.equal(reopened.history(value.alice.user.id, value.investigation.id)[0].status, 'unknown'); assert.equal(reopened.operation(value.alice.user.id, operation.id).status, 'unknown'); reopened.close(); } finally { const target = resolve(directory); assert.equal(dirname(target), resolve(tmpdir())); assert.ok(basename(target).startsWith('agents-capstone-test-')); await rm(target, { recursive: true, force: true }); }
});
test('AC-02: records and operation controls reject foreign owners; passwords and tokens stay hashed', () => {
  const value = setup(); try { const { store, alice, bob, workspace, investigation } = value; const operation = store.createOperation(alice.user.id, investigation.id, randomUUID(), 'Question', 'fixture').operation;
    for (const run of [() => store.workspace(bob.user.id, workspace.id), () => store.upload(bob.user.id, workspace.id, 'bad.md', 'Foreign document'), () => store.investigation(bob.user.id, investigation.id), () => store.operation(bob.user.id, operation.id), () => store.history(bob.user.id, investigation.id)]) assert.throws(run, error => error instanceof WorkspaceError && error.status === 404);
    assert.ok(!JSON.stringify(store.one('SELECT * FROM users WHERE id=?', alice.user.id)).includes(password)); assert.ok(!JSON.stringify(store.all('SELECT * FROM auth')).includes(alice.token)); assert.throws(() => store.login('alice@example.test', 'incorrect-password'), error => error instanceof WorkspaceError && error.status === 401); assert.equal(store.identity('alice'), null); store.logout(alice.token); assert.equal(store.identity(alice.token), null);
  } finally { value.store.close(); }
});
test('AC-03: oversized, executable, binary, traversal and malformed CSV fail before storage', () => {
  const value = setup(); try { for (const [name, content] of [['big.txt', 'x'.repeat(100001)], ['bad.exe', 'code'], ['../data.txt', 'private'], ['binary.txt', 'a\u0000b'], ['bad.csv', 'a,b\n1'], ['broken.csv', 'a,b\n"unfinished']]) assert.throws(() => value.store.upload(value.alice.user.id, value.workspace.id, name, content)); assert.equal(value.store.documents(value.alice.user.id, value.workspace.id).length, 1); assert.throws(() => validateUpload('unicode.txt', 'é'.repeat(50001))); } finally { value.store.close(); }
});
function apiFixture(docId: string, failStream = false) {
  let createCount = 0; let runs = 0; const log: any[] = []; const turns: any[] = []; const items: any[] = [];
  const api: ResearchApi = {
    create: async request => { createCount++; log.push({ create: request }); return { id: 'sess_capstone_fixture' }; },
    inspect: async () => ({ turns: [...turns], items: [...items] }),
    stream: async () => { const root = `root-${++runs}`; log.push({ subscribed: root }); return { async *[Symbol.asyncIterator]() {
      const turn = { id: root, subagent_id: null, status: 'in_progress', usage: null }; yield { type: 'agent.session.turn.in_progress', turn };
      yield { type: 'agent.session.requires_action', session: { required_actions: [{ type: 'function_call', call_id: `guidance-${runs}`, turn_id: root, name: 'read_research_guidance', arguments: {} }, { type: 'function_call', call_id: `sources-${runs}`, turn_id: root, name: 'read_sources', arguments: {} }] } };
      yield { type: 'agent.session.turn.failed', turn: { id: `child-${runs}`, subagent_id: 'child', status: 'failed' } };
      if (failStream) return;
      const message = { id: `answer-${runs}`, turn_id: root, type: 'message', role: 'assistant', content: [{ type: 'output_text', text: JSON.stringify({ findings: [{ claim: 'Search supports date filtering.', documentId: docId, quote: 'Search supports date filtering.' }], limitations: ['Child failed; root verified source directly.'] }) }] }; items.push(message); yield { type: 'agent.session.turn.item.done', item: message };
      const done = { ...turn, status: 'completed', usage: { input_tokens: 100, output_tokens: 20, total_tokens: 120 } }; turns.push(done); yield { type: 'agent.session.turn.completed', turn: done };
    } }; },
    send: async (id, events, key) => { log.push({ id, events, key }); }, remove: async id => { log.push({ removed: id }); },
  };
  return { api, log, createCount: () => createCount, turns, items };
}
test('AC-04: live adapter submits initial input once and subscribes before follow-up; keeps one mapped session', async () => {
  const value = setup(), fake = apiFixture(value.document.id), runner = new ResearchRunner(value.store, () => fake.api);
  try { for (let i = 0; i < 2; i++) { const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), `Question ${i}`, 'live'); runner.start(value.alice.user.id, entry.operation.id, true, false); await runner.jobs.get(entry.operation.id)!.done; assert.equal(value.store.operation(value.alice.user.id, entry.operation.id).status, 'completed'); }
    assert.equal(fake.createCount(), 1); const messages = fake.log.filter(row => row.events?.[0].type === 'agent.session.input.message'); assert.equal(messages.length, 1); assert.equal(fake.log.find(row => row.create).create.input, 'Question 0'); assert.ok(messages.every(row => row.id === 'sess_capstone_fixture' && row.key)); assert.ok(fake.log.findIndex(row => row.subscribed) < fake.log.findIndex(row => row.events?.[0].type === 'agent.session.input.message')); assert.equal(fake.log.find(row => row.create).create.agent.multi_agent.max_concurrent_subagents, 2);
  } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-05/AC-07: failed child does not settle root; evidence records actual function guidance and tools', async () => {
  const value = setup(), fake = apiFixture(value.document.id), runner = new ResearchRunner(value.store, () => fake.api);
  try { const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Question', 'live'); runner.start(value.alice.user.id, entry.operation.id, true, false); await runner.jobs.get(entry.operation.id)!.done; const result = value.store.operation(value.alice.user.id, entry.operation.id); assert.equal(result.evidence.root, 'completed'); assert.equal(result.evidence.turns['child-1'].status, 'failed'); assert.equal(result.evidence.guidanceReads[0].name, 'grounded-research'); assert.deepEqual(result.evidence.tools, ['read_research_guidance', 'read_sources']);
  } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-05: fixture cancellation persists a cancelled root and creates no report', async () => {
  const value = setup(), runner = new ResearchRunner(value.store); try { const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Question', 'fixture'); runner.start(value.alice.user.id, entry.operation.id, false, false); const result = await runner.stop(value.alice.user.id, entry.operation.id); assert.equal(result.status, 'cancelled'); assert.equal(result.report, null); } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-06/AC-08: unsupported quotes excluded; Markdown report and approvals use owned citations', async () => {
  const value = setup(), runner = new ResearchRunner(value.store); try { const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Question', 'fixture'); runner.start(value.alice.user.id, entry.operation.id, false, false); await runner.jobs.get(entry.operation.id)!.done; const result = value.store.publicOperation(value.alice.user.id, entry.operation.id); const checked = value.store.complete(value.alice.user.id, entry.operation.id, [{ claim: 'Invented', documentId: value.document.id, quote: 'Never exists in this source' }]); assert.equal(checked.accepted.length, 0); assert.equal(checked.rejected.length, 1); assert.ok(value.store.report(value.alice.user.id, result.report.id).content.includes(value.document.id)); assert.throws(() => value.store.report(value.bob.user.id, result.report.id), error => error instanceof WorkspaceError && error.status === 404); assert.ok(!makeReport('<script>', [], [], 'fixture').includes('<script>')); } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-09: owner approval writes exactly once, reject writes zero, stale source rejects decision', async () => {
  const value = setup(), runner = new ResearchRunner(value.store); try { const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Question', 'fixture'); runner.start(value.alice.user.id, entry.operation.id, false, false); await runner.jobs.get(entry.operation.id)!.done; const approval = value.store.publicOperation(value.alice.user.id, entry.operation.id).approvals[0]; assert.throws(() => value.store.decide(value.bob.user.id, approval.id, 'approved')); assert.equal(value.store.decide(value.alice.user.id, approval.id, 'approved').replay, false); assert.equal(value.store.decide(value.alice.user.id, approval.id, 'approved').replay, true); assert.equal(value.store.one('SELECT count(*) AS n FROM saved_findings').n, 1); assert.throws(() => value.store.decide(value.alice.user.id, approval.id, 'rejected'));
    const other = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Follow-up', 'fixture'); runner.start(value.alice.user.id, other.operation.id, false, false); await runner.jobs.get(other.operation.id)!.done; const reject = value.store.publicOperation(value.alice.user.id, other.operation.id).approvals[0]; value.store.decide(value.alice.user.id, reject.id, 'rejected'); assert.equal(value.store.one('SELECT count(*) AS n FROM saved_findings').n, 1);
    const third = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Another', 'fixture'); runner.start(value.alice.user.id, third.operation.id, false, false); await runner.jobs.get(third.operation.id)!.done; const stale = value.store.publicOperation(value.alice.user.id, third.operation.id).approvals[0]; value.store.run('UPDATE documents SET hash=? WHERE id=?', 'changed', value.document.id); assert.throws(() => value.store.decide(value.alice.user.id, stale.id, 'approved'));
  } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-10: replay is bounded and input conflicts rejected; uncertain stream is never resubmitted', async () => {
  const value = setup(), fake = apiFixture(value.document.id, true), runner = new ResearchRunner(value.store, () => fake.api); try { const key = randomUUID(); const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, key, 'Question', 'live'); assert.equal(value.store.createOperation(value.alice.user.id, value.investigation.id, key, 'Question', 'live').created, false); assert.throws(() => value.store.createOperation(value.alice.user.id, value.investigation.id, key, 'Changed', 'live')); runner.start(value.alice.user.id, entry.operation.id, false, false); await runner.jobs.get(entry.operation.id)!.done; assert.equal(value.store.operation(value.alice.user.id, entry.operation.id).status, 'unknown'); await runner.inspect(value.alice.user.id, entry.operation.id); assert.equal(fake.log.filter(row => row.create?.input || row.events?.[0].type === 'agent.session.input.message').length, 1); assert.throws(() => value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'New', 'live')); assert.equal(value.store.notification('evt_one', 'sess_capstone_fixture', 'agent.session.idle').duplicate, false); assert.equal(value.store.notification('evt_one', 'sess_capstone_fixture', 'agent.session.idle').duplicate, true);
  } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-11: versioned dataset and comparison preserve criterion gaps and adversarial results', () => { assert.equal(validateSpecification(specification).criteria.length, 12); assert.equal(evaluationDataset.cases.length, 24); const result = evaluateDataset(); assert.ok(result.results.every(row => row.outcome === 'pass')); assert.ok(result.criteria.some(row => row.outcome === 'unknown')); assert.ok(evaluateDataset(evaluationDataset, 'baseline').results.some(row => row.outcome === 'fail')); });
test('AC-04/AC-10: completed saved turn recovers a lost stream without another input', async () => {
  const value = setup(), fake = apiFixture(value.document.id, true), runner = new ResearchRunner(value.store, () => fake.api);
  try {
    const entry = value.store.createOperation(value.alice.user.id, value.investigation.id, randomUUID(), 'Question', 'live'); runner.start(value.alice.user.id, entry.operation.id, false, false); await runner.jobs.get(entry.operation.id)!.done;
    assert.equal(value.store.operation(value.alice.user.id, entry.operation.id).status, 'unknown');
    fake.turns.push({ id: 'root-1', subagent_id: null, status: 'completed', usage: null }); fake.items.push({ turn_id: 'root-1', type: 'message', role: 'assistant', content: [{ text: JSON.stringify({ findings: [{ claim: 'Date filtering is supported.', documentId: value.document.id, quote: 'Search supports date filtering.' }] }) }] });
    const recovered = await runner.inspect(value.alice.user.id, entry.operation.id); assert.equal(recovered.status, 'completed'); assert.ok(recovered.report); assert.equal(fake.log.filter(row => row.create?.input || row.events?.[0].type === 'agent.session.input.message').length, 1);
  } finally { await runner.shutdown(); value.store.close(); }
});
test('AC-12: public-origin enforcement and deployment readiness remain separate from hosted evidence', () => { const fake = { headers: { host: 'workspace.example', origin: 'https://workspace.example' }, method: 'POST' } as any; assert.equal(capstoneOrigin(fake, 'https://workspace.example'), true); assert.equal(capstoneOrigin({ ...fake, headers: { ...fake.headers, origin: 'https://evil.example' } }, 'https://workspace.example'), false); assert.equal(capstoneOrigin({ ...fake, headers: { host: 'workspace.example' } }, 'https://workspace.example'), false); });
test('Capstone HTTP routes authenticate and enforce source, session, report and approval ownership', async () => {
  const app = new CapstoneApplication(':memory:'); const server = createServer((request, response) => { const path = new URL(request.url!, 'http://localhost').pathname; void app.handle(request, response, path); }); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); const base = `http://127.0.0.1:${(server.address() as any).port}`; let cookie = '';
  const post = async (action: string, value = {}, origin = base) => { const response = await fetch(`${base}/api/capstone/${action}`, { method: 'POST', headers: { 'Content-Type': 'application/json', Origin: origin, Cookie: cookie }, body: JSON.stringify(value) }); const next = response.headers.get('set-cookie'); if (next) cookie = next.split(';')[0]; return { response, body: await response.json() as any }; };
  const get = (action: string) => fetch(`${base}/api/capstone/${action}`, { headers: { Cookie: cookie } });
  try {
    assert.equal((await get('health')).status, 200); assert.equal((await post('workspace', { name: 'No auth' })).response.status, 401); assert.equal((await post('register', { email: 'alice@example.test', password }, 'https://evil.example')).response.status, 403);
    assert.equal((await post('register', { email: 'alice@example.test', password })).response.status, 200); const aliceCookie = cookie; assert.ok(!JSON.stringify((await post('login', { email: 'alice@example.test', password })).body).includes('token')); const activeAliceCookie = cookie;
    const workspace = (await post('workspace', { name: 'Sources' })).body.workspace.id; const document = (await post('upload', { workspace, name: 'source.md', content: 'Search supports date filtering. Existing queries continue to work.' })).body.document.id; assert.ok(document);
    const investigation = (await post('investigation', { workspace, question: 'What changed?' })).body.investigation.id; const value = { investigation, requestId: randomUUID(), question: 'What changed?', mode: 'fixture', delegation: false, failure: false }; const run = await post('run', value); assert.equal(run.response.status, 202); assert.equal((await post('run', value)).body.replay, true); await app.runner.jobs.get(run.body.operation.id)!.done; const result = await (await get(`operation?id=${run.body.operation.id}`)).json() as any; const report = result.operation.report.id; const approval = result.operation.approvals[0].id;
    assert.equal((await get(`report?id=${report}`)).status, 200); cookie = ''; assert.equal((await post('register', { email: 'bob@example.test', password })).response.status, 200);
    for (const action of [`workspaces?workspace=${workspace}`, `history?investigation=${investigation}`, `operation?id=${run.body.operation.id}`, `report?id=${report}`]) assert.equal((await get(action)).status, 404);
    for (const [action, value] of [['upload', { workspace, name: 'foreign.md', content: 'Private data' }], ['approval', { id: approval, decision: 'approved' }], ['stop', { id: run.body.operation.id }], ['inspect', { id: run.body.operation.id }], ['delete-session', { investigation }]] as const) assert.equal((await post(action, value)).response.status, 404);
    assert.equal((await post('approval', { id: approval, decision: 'approved', owner: 'alice' })).response.status, 400);
    cookie = activeAliceCookie; assert.equal((await post('approval', { id: approval, decision: 'approved' })).response.status, 200); assert.equal((await post('approval', { id: approval, decision: 'approved' })).body.replay, true); assert.equal((await post('save-evaluation')).response.status, 201); assert.equal((await (await get('evaluations')).json() as any).evaluations.length, 1);
    await post('logout'); assert.equal((await get(`report?id=${report}`)).status, 401); cookie = aliceCookie; assert.equal((await get('workspaces')).status, 401);
    for (let lab = 51; lab <= 56; lab++) { const response = await fetch(`${base}/api/lab${lab}/test`, { method: 'POST', headers: { Origin: base } }); assert.equal(response.status, 200); assert.ok((await response.json() as any).results.every(row => row.passed)); }
    const savedSecret = process.env.OPENAI_WEBHOOK_SECRET; try { const secret = `whsec_${randomBytes(32).toString('base64')}`; process.env.OPENAI_WEBHOOK_SECRET = secret; app.store.setSession(investigation, 'sess_webhook_fixture'); const raw = JSON.stringify({ id: 'evt_http', type: 'agent.session.idle', data: { id: 'sess_webhook_fixture' } }); const headers = signFixture(raw, secret); for (let i = 0; i < 2; i++) { const response = await fetch(`${base}/api/capstone/webhook`, { method: 'POST', headers, body: raw }); assert.equal(response.status, 200); assert.equal((await response.json() as any).duplicate, Boolean(i)); } assert.equal((await fetch(`${base}/api/capstone/webhook`, { method: 'POST', headers, body: raw.replace('idle', 'failed') })).status, 400); } finally { if (savedSecret === undefined) delete process.env.OPENAI_WEBHOOK_SECRET; else process.env.OPENAI_WEBHOOK_SECRET = savedSecret; }
  } finally { await new Promise<void>(resolve => server.close(() => resolve())); await app.stop(); }
});
