import { DatabaseSync } from 'node:sqlite';
import { readFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { randomBytes, randomUUID, scryptSync, timingSafeEqual, createHash } from 'node:crypto';
import { validateUpload, validateFinding, type Finding, type ResearchDocument } from '../src/capstoneRules.ts';
import { researchProfile, sourceFingerprint, type ResearchProfile } from './capstoneIntegrations.ts';
export class WorkspaceError extends Error { constructor(public status: number, message: string) { super(message); } }
export const hash = (value: string) => createHash('sha256').update(value).digest('hex');
export class WorkspaceStore {
  db: DatabaseSync;
  constructor(file: string) {
    if (file !== ':memory:') mkdirSync(dirname(file), { recursive: true });
    this.db = new DatabaseSync(file); this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=5000;');
    this.db.exec(readFileSync(join(import.meta.dirname, '..', 'capstone', 'migrations', '001-workspace.sql'), 'utf8'));
    // A restarted single-process server must inspect unfinished work, never resubmit it.
    this.db.prepare("UPDATE operations SET status='unknown' WHERE status='running'").run();
  }
  close() { this.db.close(); }
  one(sql: string, ...args: any[]): any { return this.db.prepare(sql).get(...args); }
  all(sql: string, ...args: any[]): any[] { return this.db.prepare(sql).all(...args); }
  run(sql: string, ...args: any[]) { return this.db.prepare(sql).run(...args); }
  transaction<T>(fn: () => T): T { this.db.exec('BEGIN IMMEDIATE'); try { const value = fn(); this.db.exec('COMMIT'); return value; } catch (error) { this.db.exec('ROLLBACK'); throw error; } }
  credentials(email: unknown, password: unknown) { if (typeof email !== 'string' || email.length > 100 || !/^[\w.+-]+@[\w.-]+\.[a-z]{2,}$/i.test(email) || typeof password !== 'string' || password.length < 12 || password.length > 128) throw new WorkspaceError(400, 'Use a valid email and a password of 12–128 characters.'); return { email: email.toLowerCase(), password }; }
  register(email: unknown, password: unknown) { const value = this.credentials(email, password); if (this.one('SELECT count(*) AS n FROM users').n >= 100) throw new WorkspaceError(429, 'Course account limit reached.'); const salt = randomBytes(16).toString('hex'); const id = randomUUID(); try { this.run('INSERT INTO users VALUES (?,?,?,?)', id, value.email, salt, scryptSync(value.password, salt, 64).toString('hex')); } catch { throw new WorkspaceError(409, 'Account could not be created. Try signing in.'); } return this.issue(id); }
  login(email: unknown, password: unknown) { const value = this.credentials(email, password); const row = this.one('SELECT * FROM users WHERE email=?', value.email); const result = scryptSync(value.password, row?.salt || 'missing-account-salt', 64); if (!row || !timingSafeEqual(result, Buffer.from(row.password_hash, 'hex'))) throw new WorkspaceError(401, 'Email or password incorrect.'); return this.issue(row.id); }
  issue(user: string) { this.run('DELETE FROM auth WHERE expires<=?', Date.now()); if (this.one('SELECT count(*) AS n FROM auth WHERE user_id=?', user).n >= 10) throw new WorkspaceError(429, 'Sign out older sessions first.'); const token = randomBytes(32).toString('hex'); this.run('INSERT INTO auth VALUES (?,?,?)', hash(token), user, Date.now() + 3600000); return { token, user: this.one('SELECT id,email FROM users WHERE id=?', user) }; }
  identity(token: string) { return token ? this.one('SELECT users.id,users.email FROM auth JOIN users ON users.id=auth.user_id WHERE token_hash=? AND expires>?', hash(token), Date.now()) || null : null; }
  logout(token: string) { this.run('DELETE FROM auth WHERE token_hash=?', hash(token)); }
  workspace(user: string, id: string) { const row = this.one('SELECT * FROM workspaces WHERE id=? AND owner=?', id, user); if (!row) throw new WorkspaceError(404, 'Workspace not found.'); return row; }
  createWorkspace(user: string, name: unknown) { if (typeof name !== 'string' || !name.trim() || name.length > 80) throw new WorkspaceError(400, 'Workspace name must be 1–80 characters.'); if (this.one('SELECT count(*) AS n FROM workspaces WHERE owner=?', user).n >= 20) throw new WorkspaceError(429, 'Workspace limit reached.'); const id = randomUUID(); this.run('INSERT INTO workspaces VALUES (?,?,?,?)', id, user, name.trim(), Date.now()); return this.workspace(user, id); }
  documents(user: string, workspace: string): ResearchDocument[] { this.workspace(user, workspace); return this.all('SELECT id,name,content FROM documents WHERE workspace_id=? ORDER BY rowid', workspace); }
  upload(user: string, workspace: string, name: unknown, content: unknown) { this.workspace(user, workspace); const file = validateUpload(name, content); const docs = this.documents(user, workspace); if (docs.length >= 8 || docs.reduce((sum, doc) => sum + Buffer.byteLength(doc.content), 0) + Buffer.byteLength(file.content) > 250000) throw new WorkspaceError(429, 'Workspace source limit: eight documents, 250 KB total.'); const id = randomUUID(); this.run('INSERT INTO documents VALUES (?,?,?,?,?)', id, workspace, file.name, file.content, hash(file.content)); return { id, name: file.name, bytes: Buffer.byteLength(file.content) }; }
  createInvestigation(user: string, workspace: string, question: unknown) { this.workspace(user, workspace); this.question(question); if (this.one('SELECT count(*) AS n FROM investigations WHERE workspace_id=?', workspace).n >= 40) throw new WorkspaceError(429, 'Investigation limit reached.'); const id = randomUUID(); this.run('INSERT INTO investigations VALUES (?,?,?,?,?,?)', id, workspace, question, null, null, Date.now()); return this.investigation(user, id); }
  question(value: unknown) { if (typeof value !== 'string' || !value.trim() || value.length > 2000) throw new WorkspaceError(400, 'Question must be 1–2000 characters.'); }
  investigation(user: string, id: string) { const row = this.one('SELECT i.* FROM investigations i JOIN workspaces w ON w.id=i.workspace_id WHERE i.id=? AND w.owner=?', id, user); if (!row) throw new WorkspaceError(404, 'Investigation not found.'); return row; }
  snapshot(user: string, workspace?: string) { const workspaces = this.all('SELECT id,name,created FROM workspaces WHERE owner=? ORDER BY created DESC', user); if (!workspace) return { workspaces }; this.workspace(user, workspace); return { workspaces, documents: this.documents(user, workspace), investigations: this.all('SELECT id,question,mode,created FROM investigations WHERE workspace_id=? ORDER BY created DESC', workspace), findings: this.all('SELECT approval_id,finding FROM saved_findings WHERE workspace_id=?', workspace).map(row => ({ ...row, finding: JSON.parse(row.finding) })) }; }
  reserve(user: string) { return this.transaction(() => { let budget = this.one('SELECT * FROM budgets WHERE user_id=?', user); if (!budget || budget.reset <= Date.now()) { budget = { used: 0, reset: Date.now() + 60000 }; this.run('INSERT OR REPLACE INTO budgets VALUES (?,?,?)', user, 0, budget.reset); } if (budget.used >= 5) throw new WorkspaceError(429, 'Five research operations per account per minute exhausted.'); this.run('UPDATE budgets SET used=used+1 WHERE user_id=?', user); }); }
  operation(user: string, id: string) { const row = this.one('SELECT o.*,i.session_id,i.mode,i.workspace_id FROM operations o JOIN investigations i ON i.id=o.investigation_id JOIN workspaces w ON w.id=i.workspace_id WHERE o.id=? AND w.owner=?', id, user); if (!row) throw new WorkspaceError(404, 'Operation not found.'); return { ...row, evidence: JSON.parse(row.evidence) }; }
  createOperation(user: string, investigationId: string, requestId: string, question: unknown, mode: string, requestOptions: { delegation: boolean; failure: boolean; profile?: ResearchProfile } = { delegation: false, failure: false }) {
    const inv = this.investigation(user, investigationId); this.question(question); if (!/^[\w-]{16,80}$/.test(requestId) || !['fixture', 'live'].includes(mode)) throw new WorkspaceError(400, 'Invalid request ID or mode.');
    const existing = this.one('SELECT id FROM operations WHERE investigation_id=? AND request_id=?', investigationId, requestId); if (existing) { const row = this.operation(user, existing.id); if (row.question !== question || row.mode !== mode || JSON.stringify(row.evidence.requestOptions) !== JSON.stringify(requestOptions)) throw new WorkspaceError(409, 'Request ID already used for different input.'); return { operation: row, created: false }; }
    const profile = researchProfile(requestOptions.profile);
    if (mode === 'fixture' && profile !== 'sources') throw new WorkspaceError(400, 'External integrations require live mode.');
    const previous = this.one('SELECT evidence FROM operations WHERE investigation_id=? ORDER BY created DESC,rowid DESC LIMIT 1', investigationId);
    if (inv.session_id && previous) { const evidence = JSON.parse(previous.evidence); if (profile !== researchProfile(evidence.requestOptions?.profile) || requestOptions.delegation !== evidence.requestOptions.delegation) throw new WorkspaceError(409, 'Start a separate investigation to change session capabilities or delegation.'); if (profile === 'hosted' && evidence.stagedFingerprint && evidence.stagedFingerprint !== sourceFingerprint(this.documents(user, inv.workspace_id))) throw new WorkspaceError(409, 'Hosted sources changed. Start a new investigation to stage the current documents.'); }
    if (inv.mode && inv.mode !== mode) throw new WorkspaceError(409, 'Start a separate investigation to change fixture/live mode.');
    if (this.one("SELECT o.id FROM operations o JOIN investigations i ON i.id=o.investigation_id WHERE i.workspace_id=? AND o.status IN ('running','unknown')", inv.workspace_id)) throw new WorkspaceError(409, 'Settle or inspect uncertain workspace work before starting another operation.');
    if (!this.documents(user, inv.workspace_id).length) throw new WorkspaceError(400, 'Upload at least one source first.');
    this.reserve(user); const id = randomUUID(); this.run('UPDATE investigations SET mode=? WHERE id=?', mode, investigationId); this.run('INSERT INTO operations VALUES (?,?,?,?,?,?,?)', id, investigationId, requestId, 'running', question, JSON.stringify({ requestOptions, source: mode === 'live' ? 'live Agents API' : 'deterministic fixture', root: 'unknown', turns: {}, events: [], usage: null, findings: [], error: null, guidanceReads: [], tools: [] }), Date.now());
    return { operation: this.operation(user, id), created: true };
  }
  setSession(investigation: string, id: string) { this.run('UPDATE investigations SET session_id=? WHERE id=?', id, investigation); }
  update(id: string, status: string, evidence: any) { if (JSON.stringify(evidence).length > 500000) throw new WorkspaceError(400, 'Evidence size limit'); this.run('UPDATE operations SET status=?,evidence=? WHERE id=?', status, JSON.stringify(evidence), id); }
  complete(user: string, id: string, findings: any[]) {
    const operation = this.operation(user, id); const docs = this.documents(user, operation.workspace_id); const accepted: Finding[] = []; const rejected: any[] = [];
    for (const finding of findings.slice(0, 20)) { try { accepted.push(validateFinding(finding, docs)); } catch { rejected.push({ claim: typeof finding?.claim === 'string' ? finding.claim.slice(0, 1000) : 'Invalid finding', reason: 'Missing or invalid citation; needs review' }); } }
    return { accepted, rejected };
  }
  saveReport(user: string, operationId: string, content: string, findings: Finding[]) { const operation = this.operation(user, operationId); this.transaction(() => { this.run('INSERT OR IGNORE INTO reports VALUES (?,?,?,?)', randomUUID(), operationId, content, JSON.stringify(findings)); for (const finding of findings) { if (this.one('SELECT id FROM approvals WHERE operation_id=? AND finding=?', operationId, JSON.stringify(finding))) continue; const source = this.one('SELECT hash FROM documents WHERE id=? AND workspace_id=?', finding.documentId, operation.workspace_id); this.run('INSERT INTO approvals VALUES (?,?,?,?,?)', randomUUID(), operationId, JSON.stringify(finding), source.hash, 'pending'); } }); }
  publicOperation(user: string, id: string) { const operation = this.operation(user, id); const { session_id, ...publicFields } = operation; return { ...publicFields, approvals: this.all('SELECT id,finding,status FROM approvals WHERE operation_id=?', id).map(row => ({ ...row, finding: JSON.parse(row.finding) })), report: this.one('SELECT id,length(content) AS characters FROM reports WHERE operation_id=?', id) || null }; }
  history(user: string, investigation: string) { this.investigation(user, investigation); return this.all('SELECT id FROM operations WHERE investigation_id=? ORDER BY created DESC', investigation).map(row => this.publicOperation(user, row.id)); }
  decide(user: string, id: string, decision: string) {
    if (!['approved', 'rejected'].includes(decision)) throw new WorkspaceError(400, 'Choose approve or reject.');
    return this.transaction(() => { const row = this.one('SELECT a.*,i.workspace_id FROM approvals a JOIN operations o ON o.id=a.operation_id JOIN investigations i ON i.id=o.investigation_id JOIN workspaces w ON w.id=i.workspace_id WHERE a.id=? AND w.owner=?', id, user); if (!row) throw new WorkspaceError(404, 'Approval not found.'); if (row.status !== 'pending') { if (row.status !== decision) throw new WorkspaceError(409, 'Approval already decided.'); return { id, status: row.status, replay: true }; } const finding = JSON.parse(row.finding); const source = this.one('SELECT hash FROM documents WHERE id=? AND workspace_id=?', finding.documentId, row.workspace_id); if (!source || source.hash !== row.source_hash) throw new WorkspaceError(409, 'Source changed; review a new proposal.'); if (decision === 'approved') this.run('INSERT INTO saved_findings VALUES (?,?,?)', id, row.workspace_id, row.finding); this.run('UPDATE approvals SET status=? WHERE id=?', decision, id); return { id, status: decision, replay: false }; });
  }
  report(user: string, id: string) { const row = this.one('SELECT r.* FROM reports r JOIN operations o ON o.id=r.operation_id JOIN investigations i ON i.id=o.investigation_id JOIN workspaces w ON w.id=i.workspace_id WHERE r.id=? AND w.owner=?', id, user); if (!row) throw new WorkspaceError(404, 'Report not found.'); return row; }
  notification(id: string, session: string, type: string) { const mapped = this.one('SELECT id FROM investigations WHERE session_id=?', session); if (!mapped) return { ignored: true }; const result = this.run('INSERT OR IGNORE INTO webhook_events VALUES (?,?,?,?)', id, session, type, Date.now()); return { duplicate: !result.changes, inspectionRequired: true }; }
}
