import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { createServer } from 'node:http';
import { runAdvancedSuite } from '../src/advancedLabTests.ts';
import { guardedReport, guardedCsv } from '../src/lab38Guard.ts';
import { createGuardWorkspace, executeGuardTool, reviewGuardProposal, disposeGuard, guardResources } from './lab38Service.ts';
import { handleLab38, stopLab38 } from './lab38.ts';
test('shared Lab 38 suite passes', () => { for (const row of runAdvancedSuite(38)) assert.ok(row.passed, row.name); });
test('actual helper and loaded resources support the revenue contract', async () => { const workspace = await createGuardWorkspace(); try { const resources = await guardResources(); assert.equal(resources.length, 2); assert.ok(resources[0].content.includes('course-sales-report')); const result = await executeGuardTool(workspace, 'calculate_revenue', {}); assert.ok(result.success); assert.equal(result.result.total_cents, 2800); assert.equal(result.result.marker, workspace.marker); assert.equal(await readFile(join(workspace.directory, 'sales.csv'), 'utf8'), guardedCsv); } finally { await disposeGuard(workspace); } });
test('path scope denies traversal, absolute paths, null bytes and unknown write tools', async () => { const workspace = await createGuardWorkspace(); try { for (const path of ['../protected.txt', '/etc/passwd', 'C:\\Windows\\win.ini', 'report.md\0', 'sales.csv/../report.md']) assert.equal((await executeGuardTool(workspace, 'read_workspace', { path })).success, false); assert.equal((await executeGuardTool(workspace, 'apply_report', { content: guardedReport })).success, false); assert.equal(await readFile(join(workspace.directory, 'report.md'), 'utf8'), workspace.before); } finally { await disposeGuard(workspace); } });
test('proposal cannot change a file before matching approval and approval cannot be replayed', async () => { const workspace = await createGuardWorkspace(); try { assert.ok((await executeGuardTool(workspace, 'propose_report', { content: guardedReport })).success); assert.equal(await readFile(join(workspace.directory, 'report.md'), 'utf8'), workspace.before); await assert.rejects(reviewGuardProposal(workspace, 'wrong_id', 'approve')); await reviewGuardProposal(workspace, workspace.proposal!.id, 'approve'); assert.equal(await readFile(join(workspace.directory, 'report.md'), 'utf8'), guardedReport); await assert.rejects(reviewGuardProposal(workspace, workspace.proposal!.id, 'approve')); } finally { await disposeGuard(workspace); } });
test('rejection preserves content and stale content hash prevents approval', async () => { const workspace = await createGuardWorkspace(); try { await executeGuardTool(workspace, 'propose_report', { content: guardedReport }); await reviewGuardProposal(workspace, workspace.proposal!.id, 'reject'); assert.equal(await readFile(join(workspace.directory, 'report.md'), 'utf8'), workspace.before); await executeGuardTool(workspace, 'propose_report', { content: guardedReport }); await writeFile(join(workspace.directory, 'report.md'), 'Changed base'); await assert.rejects(reviewGuardProposal(workspace, workspace.proposal!.id, 'approve'), /STALE_PROPOSAL/); assert.equal(await readFile(join(workspace.directory, 'report.md'), 'utf8'), 'Changed base'); } finally { await disposeGuard(workspace); } });
test('tool budget and oversized or incorrect reports cannot create a valid proposal', async () => { const workspace = await createGuardWorkspace(); try { assert.equal((await executeGuardTool(workspace, 'propose_report', { content: guardedReport.replace('2800', '2801') })).success, false); for (let i = workspace.audit.length; i < 20; i++) await executeGuardTool(workspace, 'read_workspace', { path: 'AGENTS.md' }); assert.equal((await executeGuardTool(workspace, 'propose_report', { content: guardedReport })).success, false); assert.equal(workspace.proposal, null); } finally { await disposeGuard(workspace); } });
test('offline HTTP exercise exposes diff, requires review and disposes real fixture files', async () => {
  const server = createServer((request, response) => { void handleLab38(request, response, new URL(request.url!, 'http://localhost').pathname); }); await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve)); const base = `http://127.0.0.1:${(server.address() as any).port}`;
  async function post(action: string, body: any) { return fetch(`${base}/api/lab38/${action}`, { method: 'POST', body: JSON.stringify(body) }); }
  try { const create = await (await post('create', { requestId: 'lab38-test-request-0001' })).json(); const id = create.workspace.id; assert.equal((await (await post('create', { requestId: 'lab38-test-request-0001' })).json()).workspace.id, id); const proposal = await (await post('propose', { id, mode: 'practice' })).json(); assert.equal(proposal.workspace.current, proposal.workspace.before); assert.ok(proposal.workspace.protectedAccessDenied); assert.ok(proposal.workspace.proposal.diff.includes('2800')); const result = await (await post('review', { id, proposalId: proposal.workspace.proposal.id, decision: 'approve' })).json(); assert.equal(result.workspace.current, guardedReport); assert.equal((await post('review', { id, proposalId: proposal.workspace.proposal.id, decision: 'approve' })).status, 409); assert.equal((await post('propose', { id, mode: 'practice', path: '../external' })).status, 400); assert.equal((await fetch(`${base}/api/lab38/status`, { headers: { Origin: 'https://external.test' } })).status, 403); assert.ok((await (await post('dispose', { id })).json()).disposed); } finally { await stopLab38(); await new Promise<void>(resolve => server.close(() => resolve())); }
});
