import { useEffect, useRef, useState, type ReactNode } from 'react';
import { selectNarratorVoice } from './speech.ts';
import { runAdvancedSuite } from './advancedLabTests.ts';
import { advancedLessons } from './advancedLessons.ts';
export function downloadEvidence(value: unknown, name: string) { const url = URL.createObjectURL(new Blob([typeof value === 'string' ? value : JSON.stringify(value, null, 2)], { type: typeof value === 'string' ? 'text/plain' : 'application/json' })); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
export async function labJson(url: string, body?: unknown, signal?: AbortSignal) { const response = await fetch(url, { ...(body !== undefined ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}), signal }); const value = await response.json(); if (!response.ok) { const failure = new Error(value.error || 'Request failed') as Error & { status: number }; failure.status = response.status; throw failure; } return value; }
export function storageGet(key: string) { try { return localStorage.getItem(key) || ''; } catch { return ''; } }
export function storageSet(key: string, value: string) { try { localStorage.setItem(key, value); } catch { /* Current view still works. */ } }
export function Checks({ checks }: { checks: Array<{ name: string; passed: boolean }> }) { return <ul className="lab32-checks">{checks.map(row => <li key={row.name} className={row.passed ? 'lab29-ok' : 'lab31-error'}>{row.passed ? 'PASS' : 'NOT VERIFIED'} | {row.name}</li>)}</ul>; }
export function AdvancedLabFrame({ lab, active, title, intro, children, evidence, question }: { lab: number; active: boolean; title: string; intro: string; children: ReactNode; evidence: unknown; question: string }) {
  const [notes, setNotes] = useState(''); const [tests, setTests] = useState<ReturnType<typeof runAdvancedSuite> | null>(null); const [source, setSource] = useState(''); const [error, setError] = useState(''); const [speaking, setSpeaking] = useState<string | null>(null); const speechRun = useRef(0); const utterances = useRef<SpeechSynthesisUtterance[]>([]);
  const speechAvailable = typeof window !== 'undefined' && 'speechSynthesis' in window; const lessons = advancedLessons[lab];
  function stop() { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); utterances.current = []; setSpeaking(null); }
  useEffect(() => { if (!active) stop(); }, [active]); useEffect(() => () => { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); }, []);
  function speak(rows: typeof lessons, id: string) { if (speaking === id) { stop(); return; } stop(); if (!speechAvailable) return; const run = speechRun.current; const voice = selectNarratorVoice(window.speechSynthesis.getVoices()); utterances.current = rows.map((row, index) => { const utterance = new SpeechSynthesisUtterance(`${row.title}. ${row.explanation}`); if (voice) utterance.voice = voice; utterance.lang = voice?.lang || 'en-US'; utterance.rate = .95; utterance.onend = () => { if (run === speechRun.current && index === rows.length - 1) setSpeaking(null); }; utterance.onerror = () => { if (run === speechRun.current) { stop(); setError('Narration failed. Try an installed English voice.'); } }; return utterance; }); setSpeaking(id); utterances.current.forEach(row => window.speechSynthesis.speak(row)); }
  async function serverTests() { try { setTests((await labJson(`/api/lab${lab}/test`, {})).results); setSource('server'); setError(''); } catch (failure) { setError(failure.message); } }
  return <div className="lab16-page lab31-page lab32-page advanced-lab-page"><section className="lab-hero"><span className="eyebrow">LAB {lab} / {lab >= 44 ? 'OBSERVABILITY & OPERATIONS' : lab >= 39 ? 'MULTI-AGENT WORK' : 'HARNESS ARCHITECTURE & SECURITY'}</span><h1>{title}</h1><p>{intro}</p></section>{children}
    <section className="lab7-card"><span className="eyebrow">STUDENT CHECKPOINT</span><h2>Explain and export your evidence</h2><label htmlFor={`lab${lab}-notes`}>{question}</label><textarea id={`lab${lab}-notes`} rows={5} maxLength={5000} value={notes} onChange={event => setNotes(event.target.value)} /><button type="button" className="lab8-secondary" onClick={() => downloadEvidence({ lab, evidence, notes }, `lab${lab}-evidence.json`)}>Export evidence and notes</button></section>
    <section className="lab7-card"><span className="eyebrow">SHARED CHECKS / NO KEY REQUIRED</span><h2>Test the lab rules</h2><div className="lab30-toolbar"><button type="button" className="lab8-secondary" onClick={() => { setTests(runAdvancedSuite(lab)); setSource('browser'); }}>Run browser tests</button><button type="button" className="lab8-secondary" onClick={serverTests}>Run server tests</button></div>{tests ? <><p role="status">{tests.filter(row => row.passed).length} / {tests.length} passed | {source}</p><Checks checks={tests} /></> : null}{error ? <p role="alert" className="lab31-error">{error}</p> : null}</section>
    <details className="code-lessons lab5-code" onToggle={event => { if (!event.currentTarget.open) stop(); }}><summary className="code-lessons-toggle"><span className="code-lessons-heading"><span className="code-lessons-kicker">UNDER THE HOOD / LAB {lab}</span><span className="code-lessons-title" role="heading" aria-level={2}>How this lab was built</span><span className="code-lessons-hint">Six explained snippets with Viva voice narration.</span></span><span className="code-lessons-toggle-action">View code</span></summary><div className="code-lessons-body"><div className="lab30-toolbar"><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === 'all'} onClick={() => speak(lessons, 'all')}>Viva voice | Read all six</button><button type="button" className="lab8-secondary" disabled={!speaking} onClick={stop}>Stop narration</button></div><div className="code-lessons-grid">{lessons.map((lesson, index) => <article className="code-lesson" key={lesson.title}><div className="code-lesson-header"><span className="code-lesson-number">{String(index + 1).padStart(2, '0')}</span><div><h3>{lesson.title}</h3><span>{lesson.file}</span></div></div><pre><code>{lesson.code}</code></pre><p>{lesson.explanation}</p><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === lesson.title} onClick={() => speak([lesson], lesson.title)}>Viva voice | Read aloud</button></article>)}</div></div></details>
    <section className="lab7-card"><span className="eyebrow">OFFICIAL REFERENCES / CHECKED 2026-10-05</span><h2>Runtime and evidence references</h2><ul>{lab === 45 || lab === 46 ? <li><a href={`https://learn.chatgpt.com/docs/${lab === 45 ? 'hooks' : 'webmcp'}`} target="_blank" rel="noopener noreferrer">{lab === 45 ? 'Codex hooks' : 'Website tools'}</a></li> : null}{(lab === 36 ? ['tools/mcp', 'environments/self-hosted'] : lab === 37 ? ['environments/lifecycle', 'errors', 'sessions/events'] : lab === 38 ? ['tools/functions', 'environments/security'] : lab === 44 ? ['sessions/webhooks'] : lab === 47 ? ['tracing'] : lab === 48 || lab === 43 ? ['observability', 'multi-agent'] : lab === 49 ? ['errors'] : ['multi-agent', 'sessions/events']).map(path => <li key={path}><a href={`https://developers.openai.com/api/docs/guides/agents-api/${path}`} target="_blank" rel="noopener noreferrer">{path.replaceAll('/', ' / ')}</a></li>)}</ul></section>
  </div>;
}
