import { useState } from 'react';
import { AdvancedLabFrame, Checks } from './AdvancedLabFrame.tsx';
import { useCourseJob, LiveJobControls } from './useCourseJob.tsx';
import { delegationContract, delegationPractice, delegationRequest, verifyDelegation, childOverlap, type DelegationTrace } from './lab39Delegation.ts';
export default function DelegationLab({ active, lab }: { active: boolean; lab: 39 | 40 }) {
  const state = useCourseJob(lab, active); const [enabled, setEnabled] = useState(true); const [failure, setFailure] = useState(false); const [selected, setSelected] = useState('success'); const live = selected === 'live' && Boolean(state.job); const evidence: DelegationTrace = live ? state.job.trace : delegationPractice(lab, selected); const isEnabled = live ? state.job.enabled : selected !== 'disabled'; const isFailure = live ? state.job.failure : ['unavailable', 'child-failed'].includes(selected);
  return <AdvancedLabFrame lab={lab} active={active} title={lab === 39 ? 'Enable subagents' : 'Run independent tasks in parallel'} intro={lab === 39 ? 'Enable harness delegation, give a child a bounded contract, and verify its work separately from the root answer.' : 'Launch one child per independent source, observe overlap, and preserve an incomplete result when a child or source fails.'} evidence={{ enabled: isEnabled, failure: isFailure, trace: evidence }} question={lab === 39 ? 'Identify the root, child, creation action and returned work. How did the root check the delegation contract?' : 'Show whether child intervals overlap. Explain the failed-child and missing-source cases, the retry budget, and why a child completion cannot end the root UI.'}>
    <section className="lab7-card"><h2>Define a bounded delegation contract</h2><pre className="lab32-code">{JSON.stringify(delegationContract(lab, failure), null, 2)}</pre><p>The harness supplies coordination tools when multi_agent.enabled is true. This example uses labelled course release notes and environment.type=none. No external research, shell, function or MCP tools are configured. Children receive separate source questions and return structured findings. With a filesystem environment, root and children would share files and need an editing agreement.</p><details><summary>Actual session request</summary><pre className="lab32-code">{JSON.stringify(delegationRequest(lab, enabled, failure, state.config?.model || 'configured model'), null, 2)}</pre></details></section>
    <section className="lab7-card"><h2>Optional live delegation</h2><label className="advanced-checkbox"><input type="checkbox" checked={enabled} disabled={state.running || state.busy} onChange={event => setEnabled(event.target.checked)} /> Enable delegation for the next session</label>{lab === 40 ? <label className="advanced-checkbox"><input type="checkbox" checked={failure} disabled={state.running || state.busy} onChange={event => setFailure(event.target.checked)} /> Make source B unavailable (data failure; not an injected API child failure)</label> : null}<LiveJobControls state={state} start={() => { void state.start({ enabled, failure: lab === 40 && failure }).then(ok => { if (ok) setSelected('live'); }); }} /><p>The limit is {lab === 39 ? 'one active child' : 'two active children'}, excluding the root. A three-minute application deadline bounds observation. The prompt allows at most one follow-up per incomplete child; this is a delegation contract, not a separate API-enforced retry limit. Captured follow-up actions are checked against the budget. Actual child failure is demonstrated in a labelled synthetic case rather than forced through an undocumented API.</p></section>
    <section className="lab7-card"><h2>{lab === 39 ? 'Separate creation, child output and root verification' : 'Verify overlap and handle incomplete work'}</h2><label htmlFor={`lab${lab}-case`}>Evidence case</label><select id={`lab${lab}-case`} value={selected} onChange={event => setSelected(event.target.value)}><option value="success">Synthetic: valid delegation</option><option value="claim">Synthetic: root answer without child evidence</option><option value="disabled">Synthetic: delegation-disabled comparison</option>{lab === 40 ? <><option value="sequential">Synthetic: children finish sequentially</option><option value="unavailable">Synthetic: missing B source, explicitly incomplete</option><option value="child-failed">Synthetic: B child turn fails; root retains incomplete result</option></> : null}{state.job ? <option value="live">Current live run</option> : null}</select><p>Source: {evidence.source} | Root: {evidence.root} | Observed children: {evidence.children.length}{lab === 40 ? ` | Overlap: ${childOverlap(evidence) ? 'Observed' : 'Not established'}` : ''}</p><table><thead><tr><th>Turn</th><th>Agent</th><th>Status</th><th>Observed interval</th></tr></thead><tbody>{Object.entries(evidence.turns).map(([id, turn]) => <tr key={id}><td><code>{id}</code></td><td>{turn.child || 'root'}</td><td>{turn.status}</td><td>{turn.start ?? 'unknown'} to {turn.end ?? 'unknown'} ms</td></tr>)}</tbody></table><h3>Root answer</h3><pre className="lab32-code">{evidence.answer || 'No attributed root answer observed'}</pre><Checks checks={verifyDelegation(evidence, lab, isFailure, isEnabled)} />{evidence.error ? <p className="lab31-error">{evidence.error}</p> : null}<details><summary>Coordination actions, child messages and lifecycle</summary><pre className="lab32-code">{JSON.stringify({ items: evidence.items, events: evidence.events, cleanup: evidence.cleanup }, null, 2)}</pre></details><p>Only the root's terminal event settles the run. Text events are attributed using their turn IDs; they do not carry subagent_id. Completed creation and wait actions do not prove child completion. Overlap comes from observed child turn intervals, not a promise in the root answer. Missing intervals remain unknown.</p></section>
  </AdvancedLabFrame>;
}
