import { useEffect, useState } from 'react';
import { AdvancedLabFrame, downloadEvidence, labJson } from './AdvancedLabFrame.tsx';
import { finalLabTitles, specification, validateSpecification, evaluationDataset, validateDataset, evaluateDataset, criteria, type FinalLabId } from './capstoneRules.ts';
import ResearchWorkspace from './ResearchWorkspace.tsx';
const intros = { 51: 'Start with a reviewed, versioned specification. Keep each requirement linked to a test or observable demonstration.', 52: 'Build representative examples and failure cases with stable acceptance links and a versioned JSON schema.', 53: 'Compare settings on the same cases and keep pass, fail and unknown distinct.', 54: 'Probe enforced tool and data boundaries. Prompt instructions never replace authorization and validation.', 55: 'Package the React and Node app with persistent storage, health checks, secret handling and deployment evidence.', 56: 'Sign in, upload sources, research a question, review citations, approve a saved finding and return to the same investigation.' };
export default function FinalLab({ lab, active }: { lab: FinalLabId; active: boolean }) {
  const [json, setJson] = useState(() => JSON.stringify(lab === 51 ? specification : evaluationDataset, null, 2)); const [reviewed, setReviewed] = useState<string | null>(null); const [report, setReport] = useState<any>(null); const [setup, setSetup] = useState<any>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { if (active && lab === 55) { const controller = new AbortController(); void labJson('/api/lab55/setup', undefined, controller.signal).then(setSetup).catch(err => { if (!controller.signal.aborted) setError(err.message); }); return () => controller.abort(); } }, [active, lab]);
  async function run(server = false) { setError(''); setBusy(true); try { if (json.length > 200000) throw new Error('JSON size limit'); const value = validateDataset(JSON.parse(json)); setReport(server ? await labJson(`/api/lab${lab}/evaluate`, { dataset: value }) : { before: evaluateDataset(value, 'baseline'), after: evaluateDataset(value, 'enforced') }); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  const after = report?.after;
  return <AdvancedLabFrame lab={lab} active={active} title={finalLabTitles[lab]} intro={intros[lab]} evidence={lab === 51 ? { specification: json, reviewed, currentReview: reviewed === json } : lab === 55 ? setup : report} question={`Link your Lab ${lab} evidence to AC-01 through AC-12. Identify uncovered criteria, fixture observations and any live or hosted checks still needed.`}>
    {lab === 51 ? <section className="lab7-card"><h2>Review the specification before implementation</h2><p>This specification drives the integrated workspace in Lab 56. Version it before changing requirements. The implemented feature is a cited finding proposal that requires owner approval; the test and capstone demonstrations provide its evidence.</p><label htmlFor="lab51-spec">Versioned specification</label><textarea id="lab51-spec" rows={14} maxLength={200000} value={json} onChange={event => setJson(event.target.value)} /><div className="lab30-toolbar"><button className="lab8-secondary" onClick={() => { try { validateSpecification(JSON.parse(json)); setReviewed(json); setError(''); } catch (err) { setError(err.message); } }}>Validate and mark reviewed</button><button className="lab8-secondary" onClick={() => downloadEvidence(json, 'workspace-specification.json')}>Download specification</button></div><p role="status">{reviewed === json ? 'Reviewed version matches the current specification.' : reviewed ? 'Specification changed; review the new version.' : 'Not reviewed yet.'}</p><table><thead><tr><th>Criterion</th><th>Implementation and evidence</th></tr></thead><tbody>{criteria.map(row => <tr key={row.id}><td>{row.id}: {row.requirement}</td><td>{row.id === 'AC-12' ? 'Deployment checklist and target smoke result required' : `Capstone integration suite and Lab 56 demonstration; inspect the named ${row.id} test`}</td></tr>)}</tbody></table><p>Stable links describe where to verify; they do not mark a criterion passed. Guidance/skill and delegation evidence must state their actual runtime.</p></section> : null}
    {[52, 53, 54].includes(lab) ? <section className="lab7-card"><h2>{lab === 52 ? 'Create and validate the dataset' : lab === 53 ? 'Run reproducible before-and-after checks' : 'Red-team the enforced boundaries'}</h2><p>The prepared dataset has 24 cases mapped to acceptance criteria. It evaluates application upload, citation and tool policy. It does not claim model resistance to prompt injection. The baseline deliberately simulates accepting unvalidated requests; production routes always enforce the current policy.</p><label htmlFor={`lab${lab}-dataset`}>Versioned dataset JSON</label><textarea id={`lab${lab}-dataset`} rows={12} maxLength={200000} value={json} onChange={event => setJson(event.target.value)} /><div className="lab30-toolbar"><button disabled={busy} className="lab8-secondary" onClick={() => { try { validateDataset(JSON.parse(json)); setError(''); setReport({ validated: true, cases: JSON.parse(json).cases.length }); } catch (err) { setError(err.message); } }}>Validate dataset</button><button className="lab8-secondary" onClick={() => downloadEvidence(json, 'evaluation-dataset.json')}>Download dataset</button><button disabled={busy} className="lab8-secondary" onClick={() => run()}>Run browser evaluation</button><button disabled={busy} className="lab8-secondary" onClick={() => run(true)}>Run Node evaluation</button></div><p>CLI: node --import tsx scripts/evaluate-capstone.ts --out .lab-data/evaluation-report.json</p>{after ? <><p role="status">Before: {report.before.results.filter(row => row.outcome === 'pass').length}/{report.before.results.length} passed | After: {after.results.filter(row => row.outcome === 'pass').length}/{after.results.length} passed | Dataset {after.datasetVersion}</p><table><thead><tr><th>Case / criterion</th><th>Expected → actual</th><th>Outcome</th><th>Details</th></tr></thead><tbody>{after.results.filter(row => lab !== 54 || row.split === 'red-team').map(row => <tr key={row.id}><td>{row.id}: {row.criteria.join(', ')}<br />{row.prompt}</td><td>{row.expected} → {row.actual}</td><td>{row.outcome}</td><td>{row.detail || 'Policy accepted the validated request'}</td></tr>)}</tbody></table><h3>Criterion coverage and gaps</h3><ul>{after.criteria.map(row => <li key={row.id}>{row.id}: {row.outcome} — {row.reason}</li>)}</ul><button className="lab8-secondary" onClick={() => downloadEvidence(report, `lab${lab}-regression-report.json`)}>Download report</button></> : <p>Run evaluation to inspect reproducible results and unknown coverage.</p>}{lab === 54 ? <p>Fixes exercised here: scoped source functions, strict arguments, executable/path rejection, exact citation matching and a separate owner approval route. Test live model behavior with adversarial uploaded text in Lab 56 and review its actual trace. Passing deterministic boundaries does not prove safe answers.</p> : null}</section> : null}
    {lab === 55 ? <section className="lab7-card"><h2>Deploy the capstone independently</h2><p>The deployment exposes the capstone API and final-lab policy checks. Earlier teaching APIs are excluded from this server. Use the supplied Docker image, a persistent volume and one replica for SQLite.</p><pre className="lab32-code">docker compose -f capstone/deploy/compose.yaml up --build -d</pre><p>Open http://localhost:8080/#lab56. Health endpoint: /api/capstone/health. Configure CAPSTONE_PUBLIC_ORIGIN to the exact external origin behind your HTTPS proxy. Set OPENAI_API_KEY as a server secret for optional live research. Hosted registration is disabled unless CAPSTONE_ALLOW_REGISTRATION=true. No secrets belong in the image.</p><pre className="lab32-code">node --import tsx scripts/smoke-capstone.ts http://localhost:8080</pre><p>The smoke script registers two temporary course accounts, uploads a source, creates a fixture investigation, verifies foreign access rejection, approves a finding twice and downloads its report. Keep its accounts as labelled test data or remove them using an administrator-managed retention process.</p><h3>Deployment checklist</h3><ul><li>Image build and current process health</li><li>HTTPS origin, secure cookies and explicit registration policy</li><li>Persistent SQLite volume, one replica, encrypted backups and retention</li><li>Server secrets, application budgets and provider spend controls</li><li>Two-user ownership smoke, report download and approval replay</li><li>Live session cancellation/deletion and shutdown recovery</li><li>External target smoke evidence and documented remaining gaps</li></ul><pre className="lab32-code">{JSON.stringify(setup, null, 2)}</pre><p>A local process or container check is not evidence that a remote hosting target has been deployed. Follow capstone/deploy/README.md for target configuration and retention.</p></section> : null}
    {lab === 56 ? <ResearchWorkspace active={active} /> : null}
    {error ? <p role="alert" className="lab31-error">{error}</p> : null}
  </AdvancedLabFrame>;
}
