import type { EnvironmentKind, HarnessTrace, StepKind, TraceStep } from './lab31Harness.ts';
function step(id: string, kind: StepKind, label: string, detail: string, status: string | null = null, root = true): TraceStep {
  return { id, kind, label, detail, status, root, turnId: ['session', 'environment', 'input', 'submit'].includes(kind) ? null : 'turn_practice', callId: kind.startsWith('function_') ? 'call_practice' : null };
}
const common = [step('input', 'input', 'Student enters a task', 'The React form collects a question.'), step('submit', 'submit', 'Server submits input', 'Credentials stay on the Node server.'), step('session', 'session', 'Session created', 'The managed service stores session configuration and progress.', 'idle')];
function trace(title: string, environment: EnvironmentKind, steps: TraceStep[], warning: string | null = null): HarnessTrace {
  return { version: 1, source: 'synthetic practice', title, sessionId: 'sess_practice_lab31', environment, complete: true, warning, steps: [...common, ...steps] };
}
export const harnessScenarios: Array<{ id: string; trace: HarnessTrace }> = [
  { id: 'hosted', trace: trace('Hosted computation', 'openai_hosted', [step('ready', 'environment', 'Sandbox becomes ready', 'OpenAI provisions the environment before sandbox work starts.', 'ready'), step('working', 'turn', 'Root turn in progress', 'The harness coordinates the model/tool loop.', 'in_progress'), step('command', 'command', 'command_execution', 'python3 -c "print(sum(range(1, 101)))" → 5050; exit 0.', 'completed'), step('text', 'text', 'Assistant reports 5050', 'Text matches the demonstrated command output.', 'completed'), step('done', 'turn', 'Root turn completed', 'The root outcome ends the task.', 'completed'), step('render', 'render', 'React renders the report', 'Displaying text does not perform the computation.')]) },
  { id: 'function', trace: trace('Application function boundary', 'none', [step('working', 'turn', 'Root turn starts', 'No sandbox is needed for a server function.', 'in_progress'), step('call', 'function_call', 'lookup_course_calendar proposed', 'The model proposes an application function; the proposal cannot approve a write.'), step('waiting', 'turn', 'requires_action', 'The harness waits for an application result.', 'waiting'), step('result', 'function_result', 'Server returns function_call_output', 'The handler validates input, reads the course calendar, and supplies the matching call ID.', 'completed'), step('answer', 'text', 'Assistant uses the calendar result', 'The managed loop resumes with the supplied result.'), step('done', 'turn', 'Root turn completed', 'All required application calls were answered.', 'completed')]) },
  { id: 'mcp', trace: trace('Remote MCP without a sandbox', 'none', [step('mcp', 'mcp_call', 'openai_docs / fetch_openai_doc', 'A configured service-origin connection reaches the public MCP server.', 'completed'), step('answer', 'text', 'Assistant cites the page', 'The MCP service supplied the documentation; the model wrote the answer.'), step('done', 'turn', 'Root turn completed', 'The harness finished with no workspace commands.', 'completed')]) },
  { id: 'disconnect', trace: trace('Reader disconnect and child completion', 'openai_hosted', [step('working', 'turn', 'Root turn in progress', 'Root work is still active.', 'in_progress'), step('child', 'turn', 'A child turn completes', 'Completion belongs to a subagent, not the root.', 'completed', false), step('idle', 'session', 'Observed session state', 'A session state observation is not root turn success.', 'idle'), step('disconnect', 'disconnect', 'Browser stops reading', 'The reader ended; retrieve saved state before resending.')], 'This synthetic trace deliberately has no root terminal outcome.') },
  { id: 'failure', trace: trace('Provisioning failure', 'openai_hosted', [step('setup', 'environment', 'environment.failed', 'Sandbox setup failed. No root turn was started.', 'failed')], 'Environment failure is distinct from a failed root turn.') },
  { id: 'self-hosted', trace: trace('Self-hosted ownership preview', 'self_hosted', [step('provision', 'submit', 'Application connects its executor', 'Your infrastructure owns compute setup, reconnection, and shutdown.'), step('ready', 'environment', 'Executor connected', 'The managed harness remains on OpenAI while commands run on your compute.', 'ready'), step('command', 'command', 'Workspace command executes', 'A connected executor runs the requested command.', 'completed'), step('done', 'turn', 'Root turn completed', 'Application coordinates retention and shutdown separately.', 'completed')], 'Architecture practice only. This lab does not provision a self-hosted executor; Lab 32 covers that implementation.') },
];
export const ownershipQuestions = [
  { id: 'loop', question: 'Who runs the model/tool loop in the Agents API?', owner: 'harness', why: 'The managed Codex harness coordinates the agent loop.' },
  { id: 'proposal', question: 'Who proposes an application function call?', owner: 'model', why: 'The model proposes an action; a declaration is not executable code.' },
  { id: 'handler', question: 'Who validates and executes your application function?', owner: 'server', why: 'Your handler enforces product rules and returns the result.' },
  { id: 'command', question: 'Where does a built-in shell command execute?', owner: 'sandbox', why: 'The environment supplies compute and workspace files.' },
  { id: 'secret', question: 'Where does this course app keep its API key?', owner: 'server', why: 'The Node server owns the credential; React calls local routes.' },
  { id: 'mcp', question: 'Who implements a remote MCP tool?', owner: 'mcp', why: 'The service provides the implementation; the harness coordinates the call.' },
  { id: 'voice', question: 'Where does Viva voice narration play?', owner: 'browser', why: 'Browser speech synthesis reads the lesson explanations locally.' },
] as const;
