export const cleanupLessons = [
  {
    number: '01', title: 'Inspect the session, turn, and sandbox', file: 'server/lab30.ts',
    code: "const session = await api.beta.agents.sessions.retrieve(id);\nconst turns = await api.beta.agents.sessions.turns.list(id, {\n  order: 'desc', limit: 1,\n});\nconst environment = await api.beta.agents.environments.retrieve(\n  session.environment.id,\n);\n// Session idle does not prove sandbox setup has finished.",
    explanation: 'Cleanup starts with evidence. Retrieve the session, its latest turn, and the environment. The session can be idle while the sandbox is still provisioning. A turn can also be waiting on a required action. This lab checks all three states and blocks deletion when setup or work is still active, or when environment state is unknown. Listing is read only. Choosing a session for inspection does not delete it. The live list belongs to the API key’s project, so inspect the session you intend to clean up.'
  },
  {
    number: '02', title: 'Keep the outputs you need', file: 'server/lab30.ts',
    code: "for await (const artifact of api.beta.agents.sessions.artifacts.list(id)) {\n  // Review path AND turn_id, including previous versions.\n  const response = await api.beta.agents.sessions.artifacts.content(\n    artifact.id, { session_id: id },\n  );\n  // Download through your server; verify size and SHA-256.\n}\n// The checklist asks the user to confirm retention separately.",
    explanation: 'Published artifacts are immutable copies associated with a session. They survive sandbox expiration, but you should download needed outputs before deleting the session. Review the turn identifier as well as the path, because revisions have separate artifact identifiers. The download proxy checks metadata and byte count, then the browser verifies a SHA two fifty six hash before offering the file to save. Offering a download does not prove it was saved. Confirm that needed files are retained, or explicitly decide that no outputs are needed. Scratch files outside the outputs directory are not published artifacts.'
  },
  {
    number: '03', title: 'Stop input and cancel active work explicitly', file: 'server/lab30.ts',
    code: "await api.beta.agents.sessions.events.create(id, {\n  events: [{ type: 'agent.session.input.cancel' }],\n});\n// Request accepted is not the same as turn cancelled.\n// Wait, then retrieve session and latest turn again.\n// stream.controller.abort() closes the reader only.",
    explanation: 'Stop sending new input before cleanup. If the turn is still active and you want to abandon it, explicitly request cancellation. Closing a stream only stops that reader; it does not cancel execution. A successful cancellation request is not evidence of a terminal turn. Wait and inspect again until the latest turn is completed, failed, or cancelled and no required actions remain. Cancelling can abandon unpublished outputs, so the page requires the selected session identifier for cancellation too. The lab coordinates its own cleanup operations, while the API remains responsible for conflicts with other writers.'
  },
  {
    number: '04', title: 'Recheck before deletion and bound retries', file: 'server/lab30Service.ts',
    code: "for (let attempt = 1; attempt <= 3; attempt++) {\n  const fresh = await api.inspect(inspected.id);\n  if (snapshotKey(fresh) !== snapshotKey(inspected))\n    throw new Error('Inspect again: session changed.');\n  try { return await api.delete(inspected.id); }\n  catch (error) {\n    if (!retryDelete(error.status, attempt)) throw error;\n    await pause(retryDelay(attempt));\n  }\n}",
    explanation: 'The server issues an inspection ticket that expires after ten minutes. Before every deletion attempt it retrieves fresh state and compares the turn, activity, environment, and artifact inventory with the reviewed snapshot. Any change requires another inspection. A conflict response with status four oh nine can mean setup or execution is finishing. The server makes at most three attempts, waiting half a second and then one second, with another state check before each retry. Authentication errors and other failures stop immediately. The OpenAI client’s automatic retries are disabled here so the lesson’s attempt limit is real.'
  },
  {
    number: '05', title: 'Verify API absence and export evidence', file: 'server/lab30Service.ts',
    code: "const result = await api.beta.agents.sessions.delete(id);\n// Require result.deleted === true.\ntry {\n  await api.beta.agents.sessions.retrieve(id);\n  // Still retrievable: verification pending.\n} catch (error) {\n  // Only status 404 verifies API absence.\n  // 403, 500, and network failures prove nothing.\n}\n// Export the inspection, download hashes, attempts, and result.",
    explanation: 'Deletion confirmation and verification answer different questions. The deleted flag confirms that the API accepted deletion. A follow up retrieval returning four oh four verifies that the session is no longer accessible through that API. A permission error or network timeout cannot verify absence. The page keeps the deletion result if verification is inconclusive and provides a separate verify again action. Physical cleanup can continue asynchronously after the session disappears. Export the checklist and audit result as evidence, without claiming that you observed the underlying container being destroyed.'
  },
  {
    number: '06', title: 'Understand retention and environment ownership', file: 'src/lab30Cleanup.ts',
    code: "// openai_hosted: delete the session to request sandbox cleanup.\n// Published artifacts survive sandbox expiry.\n// Save needed outputs BEFORE deleting the session.\n// Removing one artifact leaves its live sandbox file intact.\n// self_hosted: coordinate session deletion AND provider shutdown.\n// This page accepts only openai_hosted sessions.",
    explanation: 'Expiration, artifact deletion, and session deletion have different effects. A hosted sandbox can expire when activity and keep alives stop for an hour. That timeout is not configurable and idle time in this page is not an expiry countdown. Published outputs survive that expiry. Deleting one published artifact leaves its live sandbox file intact. Deleting a hosted session requests sandbox cleanup. A self hosted session also needs a separate provider shutdown; deleting its API session does not stop its compute. This lab focuses on OpenAI hosted sessions and does not attempt to stop external infrastructure. Cleanup practice scenarios are synthetic examples, clearly labelled, and never call the API.'
  },
];
