import { useEffect, useRef, useState } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-typescript';
import { codeTokens } from './Lab22.tsx';
import { selectNarratorVoice } from './speech.ts';
import { capabilityDirectory, inspectManifest, skillCases, skillEnvironment, skillImage, skillObservations, skillPractice, verifySkillEvidence, type SkillTask } from './lab34Skills.ts';
import { runSkillSuite } from './lab34Tests.ts';
import { skillLessons } from './lab34Lessons.ts';
import type { SkillJob } from '../server/lab34.ts';
const saved = (key: string) => { try { return localStorage.getItem(key) || ''; } catch { return ''; } };
const save = (key: string, value: string) => { try { localStorage.setItem(key, value); } catch { /* Current view still works. */ } };
function download(text: string, filename: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function json(url: string, body?: unknown, signal?: AbortSignal) { const response = await fetch(url, { ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}), signal }); const value = await response.json(); if (!response.ok) throw new Error(value.error || 'Request failed.'); return value; }
export default function Lab34({ active }: { active: boolean }) {
  const [files, setFiles] = useState<Array<{ path: string; content: string }>>([]); const [draft, setDraft] = useState(''); const [file, setFile] = useState('SKILL.md');
  const [task, setTask] = useState<SkillTask>('revenue'); const [registered, setRegistered] = useState(true);
  const [config, setConfig] = useState<{ enabled: boolean; applicationKey: boolean; executorKey: boolean; model: string } | null>(null); const [setup, setSetup] = useState(0); const [checking, setChecking] = useState(false);
  const [job, setJob] = useState<SkillJob | null>(null); const [jobId, setJobId] = useState(() => saved('lab34-job')); const [selected, setSelected] = useState<string>('revenue');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notes, setNotes] = useState(''); const [tests, setTests] = useState<ReturnType<typeof runSkillSuite> | null>(null); const [testSource, setTestSource] = useState('');
  const [speaking, setSpeaking] = useState<string | null>(null); const speechRun = useRef(0); const utterances = useRef<SpeechSynthesisUtterance[]>([]);
  const speechAvailable = typeof window !== 'undefined' && 'speechSynthesis' in window && typeof SpeechSynthesisUtterance !== 'undefined';
  function stopSpeech() { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); utterances.current = []; setSpeaking(null); }
  useEffect(() => { if (!active) stopSpeech(); }, [active]);
  useEffect(() => () => { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); }, []);
  useEffect(() => {
    if (!active) return; const controller = new AbortController(); setChecking(true);
    void Promise.all([json('/api/lab34/status', undefined, controller.signal), json('/api/lab34/skill', undefined, controller.signal)])
      .then(([status, bundle]) => { if (controller.signal.aborted) return; setConfig(status); setFiles(bundle.files); setDraft(current => current || bundle.files.find(row => row.path === 'SKILL.md')?.content || ''); setError(''); })
      .catch(failure => { if (!controller.signal.aborted) { setConfig(null); setError(failure.message); } }).finally(() => { if (!controller.signal.aborted) setChecking(false); });
    return () => controller.abort();
  }, [active, setup]);
  useEffect(() => {
    if (!active || !jobId) return; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    async function poll() { try { const data = await json(`/api/lab34/job?id=${encodeURIComponent(jobId)}`, undefined, controller.signal); if (controller.signal.aborted) return; setJob(data.job); if (data.job.status === 'running') timer = setTimeout(poll, 1000); } catch (failure) { if (!controller.signal.aborted) { setError(`${failure.message} If the server restarted, check the named Docker container and saved API session.`); timer = setTimeout(poll, 5000); } } }
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [active, jobId]);
  function speak(queue: typeof skillLessons, all = false) {
    const marker = all ? 'all' : queue[0].number; if (speaking === marker) { stopSpeech(); return; } stopSpeech(); if (!speechAvailable) return;
    const run = speechRun.current; const voice = selectNarratorVoice(window.speechSynthesis.getVoices());
    utterances.current = queue.map((lesson, index) => { const utterance = new SpeechSynthesisUtterance(`${lesson.title}. ${lesson.explanation}`); if (voice) utterance.voice = voice; utterance.lang = voice?.lang || 'en-US'; utterance.rate = .95; utterance.onend = () => { if (run === speechRun.current && index === queue.length - 1) setSpeaking(null); }; utterance.onerror = () => { if (run === speechRun.current) { stopSpeech(); setError('Narration could not play. Try an installed English voice.'); } }; return utterance; }); setSpeaking(marker); utterances.current.forEach(utterance => window.speechSynthesis.speak(utterance));
  }
  async function start() { setBusy(true); setError(''); const requestId = saved('lab34-request') || crypto.randomUUID(); save('lab34-request', requestId);
    try { const data = await json('/api/lab34/run', { requestId, task, registered }); setJob(data.job); setJobId(data.job.id); save('lab34-job', data.job.id); save('lab34-request', ''); setSelected('live'); } catch (failure) { setError(`${failure.message} Retry keeps the same request ID to avoid duplicate compute.`); } finally { setBusy(false); }
  }
  async function control(action: 'stop' | 'cleanup') { if (!job) return; setBusy(true); setError(''); try { setJob((await json(`/api/lab34/${action}`, { id: job.id })).job); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  async function serverTests() { try { setTests((await json('/api/lab34/test', {})).results); setTestSource('server'); } catch (failure) { setError(failure.message); } }
  const live = selected === 'live' && Boolean(job); const evidence = live ? job! : skillPractice(skillCases.find(row => row.id === selected)?.id ?? 'revenue');
  const trace = evidence.trace; const observed = skillObservations(trace); const checks = verifySkillEvidence(evidence); const manifest = inspectManifest(draft); const running = job?.status === 'running'; const cleanupFailed = job?.trace.cleanup === 'failed' || job?.sessionCleanup === 'failed';
  const blockers = [...(!config ? ['Server setup is not available. Use localhost and recheck setup.'] : [...(!config.enabled ? ['Set LAB34_ENABLE_LOCAL_EXECUTOR=true in .env.'] : []), ...(!config.applicationKey ? ['Configure OPENAI_API_KEY in .env.'] : []), ...(!config.executorKey ? ['Configure a distinct restricted OPENAI_EXECUTOR_API_KEY in .env.'] : [])]), ...(running ? ['Wait for the current run or stop it.'] : []), ...(cleanupFailed ? ['Retry cleanup before starting another run.'] : [])];
  return <div className="lab16-page lab31-page lab32-page lab34-page">
    <section className="lab-hero"><span className="eyebrow">LAB 34 / STANDALONE SKILLS</span><h1>Create and discover standalone skills</h1><p>Author a focused skill, register its sandbox directory, and verify relevant use with command evidence.</p><div className="lab26-hero-badges"><span>SKILL.md</span><span>References and scripts</span><span>Capability directories</span></div></section>
    <section className="lab7-card"><span className="eyebrow">SKILL AUTHORING / NO KEY REQUIRED</span><h2>Give the model a precise discovery signal</h2><p>Inspect the actual skill files included in the executor image. The name and description are discovery metadata; the body, reference and helper support the selected task.</p><label htmlFor="lab34-file">Bundled file</label><select id="lab34-file" value={file} onChange={event => setFile(event.target.value)}>{files.length ? files.map(row => <option key={row.path}>{row.path}</option>) : <option>SKILL.md</option>}</select><pre className="lab32-code">{files.find(row => row.path === file)?.content || 'Loading bundled files…'}</pre>
      <label htmlFor="lab34-draft">Write a SKILL.md draft</label><textarea id="lab34-draft" rows={10} maxLength={8000} value={draft} onChange={event => setDraft(event.target.value)} /><ul className="lab32-checks">{manifest.checks.map(check => <li key={check.name} className={check.passed ? 'lab29-ok' : 'lab31-error'}>{check.passed ? 'PASS' : 'NOT VERIFIED'} · {check.name}</li>)}</ul><p className="lab8-note">These authoring checks support the fixture’s plain, single-line name and description fields; they are not a complete YAML parser. Draft edits do not change the reviewed live image. To try your own skill, edit the source files and rebuild the image.</p><div className="lab30-toolbar"><button type="button" className="lab8-secondary" disabled={!draft} onClick={() => download(draft, 'SKILL.md', 'text/markdown')}>Download draft SKILL.md</button><button type="button" className="lab8-secondary" disabled={!files.length} onClick={() => setDraft(files.find(row => row.path === 'SKILL.md')?.content || '')}>Restore bundled manifest</button></div>
    </section>
    <section className="lab7-card"><span className="eyebrow">REGISTRATION AND PACKAGING</span><h2>Make the skill available inside the sandbox</h2><pre className="lab32-code">{JSON.stringify({ environment: skillEnvironment(registered) }, null, 2)}</pre><p>The image already contains <code>{capabilityDirectory}/course-sales-report/SKILL.md</code>. Register the absolute parent directory inside the sandbox. Use up to 32 unique paths without dot or parent segments. A host directory is not an executor directory.</p><table className="lab33-comparison"><thead><tr><th>Standalone skill (Lab 34)</th><th>Plugin-bundled skill (Lab 25)</th></tr></thead><tbody><tr><td>SKILL.md, references and helper scripts</td><td>Plugin manifest plus bundled skills and integrations</td></tr><tr><td>Register a skill parent in capability_directories</td><td>Hosted plugin installation, or a self-hosted plugin root in capability_directories</td></tr><tr><td>This report skill adds no MCP server</td><td>Lab 25 packages documentation skills with an MCP connection</td></tr></tbody></table><p>Registration is configuration evidence. A read and helper command provide separate evidence of use. Skill instructions guide behavior; sandbox permissions enforce access.</p></section>
    <section className="lab7-card"><span className="eyebrow">OPTIONAL LIVE SELF-HOSTED RUN</span><h2>Test relevance in a disposable executor</h2><details open={Boolean(config && blockers.length)}><summary>Setup before the first live run</summary><ol><li>Run Docker Desktop in Linux container mode.</li><li>Build the image: <pre className="lab32-code">docker build -t {skillImage} sandbox/lab34</pre></li><li>Configure OPENAI_API_KEY, a distinct restricted OPENAI_EXECUTOR_API_KEY, and LAB34_ENABLE_LOCAL_EXECUTOR=true in .env. Restart the course server.</li><li>The restricted key must share the session’s organization, project and owner, and have only environment-connection permissions. Pin CODEX_VERSION to a verified exact CLI version for reproducible recordings.</li></ol></details><div className="lab31-facts"><span><strong>Local executor</strong>{config?.enabled ? 'Enabled' : 'Disabled'}</span><span><strong>Application key</strong>{config?.applicationKey ? 'Configured' : 'Not configured'}</span><span><strong>Restricted key</strong>{config?.executorKey ? 'Configured' : 'Not configured'}</span><span><strong>Model</strong>{config?.model || 'Checking…'}</span></div>
      <label htmlFor="lab34-task">Task</label><select id="lab34-task" value={task} disabled={running || busy} onChange={event => setTask(event.target.value as SkillTask)}><option value="revenue">Relevant: revenue report from a fresh CSV</option><option value="unrelated">Unrelated: explain Python tuples and lists</option></select><label className="lab34-checkbox"><input type="checkbox" checked={registered} disabled={running || busy} onChange={event => setRegistered(event.target.checked)} /> Register the standalone skill parent for the next run</label><div id="lab34-blockers" aria-live="polite">{blockers.length ? <ul>{blockers.map(reason => <li key={reason}>{reason}</li>)}</ul> : null}</div><div className="lab30-toolbar"><button type="button" className="lab8-secondary" disabled={checking} onClick={() => setSetup(value => value + 1)}>{checking ? 'Checking…' : 'Recheck setup'}</button><button type="button" className="lab8-run" disabled={Boolean(blockers.length) || busy || checking} aria-describedby="lab34-blockers" onClick={start}>{running ? 'Run in progress…' : 'Connect and run task'}</button><button type="button" className="lab8-secondary" disabled={!running || busy} onClick={() => control('stop')}>Stop run and clean up</button><button type="button" className="lab8-secondary" disabled={!cleanupFailed || running || busy} onClick={() => control('cleanup')}>Retry cleanup</button></div><p className="lab8-note">Each run creates an API session and a fresh Docker container with bounded temporary storage. No host project or Docker socket is mounted. Outbound networking is available. The executor can read its restricted key. The job has a five-minute deadline and a two-minute connection wait. Browser navigation leaves the server job running; reopening resumes polling its saved ID.</p>{job ? <p>Run: <code>{job.id}</code> · {job.status} · Container: <code>{job.containerName}</code> · API cleanup: {job.sessionCleanup}</p> : null}{error ? <p role="alert" className="lab31-error">{error}</p> : null}</section>
    <section className="lab7-card"><span className="eyebrow">PRACTICE AND OBSERVED EVIDENCE</span><h2>Available, read, executed and useful are separate claims</h2><label htmlFor="lab34-case">Evidence case</label><select id="lab34-case" value={selected} onChange={event => setSelected(event.target.value)}>{skillCases.map(row => <option key={row.id} value={row.id}>{row.title}</option>)}{job ? <option value="live">Current live run</option> : null}</select><p>{live ? 'Actual server-run evidence. Registration does not imply successful discovery or selection.' : 'Synthetic practice only. These cases are teaching fixtures, not recorded model output.'}</p><div className="lab31-facts"><span><strong>Source</strong>{trace.source}</span><span><strong>Registered</strong>{evidence.registered ? 'Yes' : 'No'}</span><span><strong>Connection</strong>{trace.connection}</span><span><strong>Root outcome</strong>{trace.outcome}</span></div><p>Session: <code>{trace.sessionId ?? 'practice'}</code> · Manifest read: {observed.manifestRead ? 'Observed' : 'Not verified'} · Reference read: {observed.referenceRead ? 'Observed' : 'Not verified'} · Helper: {observed.helperRun ? 'Observed' : 'Not verified'}</p>{trace.error ? <p role="status" className="lab31-error">{trace.error}</p> : null}<details><summary>Lifecycle events</summary><ol className="lab32-events">{trace.events.map((event, index) => <li key={index}><code>{event.name}</code><span>{event.ms} ms</span></li>)}</ol></details><h3>Completed command evidence</h3>{trace.commands.length ? trace.commands.map(command => <div key={command.id}><p>Exit: {command.exitCode ?? 'unknown'} · Directory: {command.cwd || 'not reported'}</p><pre className="lab32-code">{command.command}{'\n\n'}{command.output || 'No captured output'}</pre></div>) : <p>No completed commands observed.</p>}<h3>Final answer</h3><pre className="lab32-code">{trace.answer || 'No final answer observed.'}</pre><ul className="lab32-checks">{checks.map(check => <li key={check.name} className={check.passed ? 'lab29-ok' : 'lab31-error'}>{check.passed ? 'PASS' : 'NOT VERIFIED'} · {check.name}</li>)}</ul><p className="lab8-note">A matching answer does not prove a skill read. For unrelated tasks, “no observed use” applies to captured commands only. Other file-read mechanisms or truncated output may require manual runtime inspection. This checker establishes consistency for the fixture, not causal proof or a general evaluation of skill quality.</p></section>
    <section className="lab7-card"><span className="eyebrow">STUDENT EVIDENCE</span><h2>Explain progressive disclosure and relevance</h2><label htmlFor="lab34-notes">What was registered, what was read, what executed, and why was the skill relevant?</label><textarea id="lab34-notes" rows={5} maxLength={5000} value={notes} onChange={event => setNotes(event.target.value)} /><button type="button" className="lab8-secondary" onClick={() => download(JSON.stringify({ evidence: live ? job : evidence, checks, notes }, null, 2), 'lab34-skill-evidence.json', 'application/json')}>Export evidence</button><p>Challenge: collect a relevant-task trace, an unrelated-task trace and a registration-disabled comparison. Explain a correct answer without skill evidence, an unnecessary activation, and the difference from Lab 25’s plugin packaging.</p></section>
    <section className="lab7-card"><span className="eyebrow">SHARED TEST PAGE / NO KEY REQUIRED</span><h2>Check registration and evidence rules</h2><div className="lab30-toolbar"><button type="button" className="lab8-secondary" onClick={() => { setTests(runSkillSuite()); setTestSource('browser'); }}>Run browser tests</button><button type="button" className="lab8-secondary" onClick={serverTests}>Run server tests</button></div>{tests ? <><p role="status">{tests.filter(row => row.passed).length} / {tests.length} passed · {testSource}</p><ul className="lab30-test-list">{tests.map(row => <li key={row.name}>{row.passed ? 'PASS' : 'FAIL'} · {row.name}</li>)}</ul></> : null}</section>
    <details className="code-lessons lab5-code" onToggle={event => { if (!event.currentTarget.open) stopSpeech(); }}><summary className="code-lessons-toggle"><span className="code-lessons-heading"><span className="code-lessons-kicker">UNDER THE HOOD · LAB 34</span><span className="code-lessons-title" role="heading" aria-level={2}>How the standalone skills lab was built</span><span className="code-lessons-hint">Six explained snippets with Viva voice narration.</span></span><span className="code-lessons-toggle-action">View code</span></summary><div className="code-lessons-body"><div className="lab30-toolbar"><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === 'all'} onClick={() => speak(skillLessons, true)}>Viva voice · Read all six</button><button type="button" className="lab8-secondary" disabled={!speaking} onClick={stopSpeech}>Stop narration</button></div><div className="code-lessons-grid">{skillLessons.map(lesson => <article className="code-lesson" key={lesson.number}><div className="code-lesson-header"><span className="code-lesson-number">{lesson.number}</span><div><h3>{lesson.title}</h3><span>{lesson.file}</span></div></div><pre><code>{codeTokens(Prism.tokenize(lesson.code, Prism.languages.typescript || Prism.languages.javascript))}</code></pre><p>{lesson.explanation}</p><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === lesson.number} onClick={() => speak([lesson])}>Viva voice · Read aloud</button></article>)}</div></div></details>
    <section className="lab7-card"><span className="eyebrow">OFFICIAL REFERENCES / CHECKED 2026-10-04</span><h2>Skill discovery and sandbox registration</h2><ul><li><a href="https://developers.openai.com/api/docs/guides/tools-skills" target="_blank" rel="noopener noreferrer">Skills and Agents API capability directories</a></li><li><a href="https://developers.openai.com/api/docs/guides/agents-api/tools/plugins" target="_blank" rel="noopener noreferrer">Plugin-bundled skills</a></li><li><a href="https://developers.openai.com/api/docs/guides/agents-api/environments/self-hosted" target="_blank" rel="noopener noreferrer">Self-hosted executor connection</a></li></ul></section>
  </div>;
}
