import { useState } from 'react';
import { AdvancedLabFrame, Checks } from './AdvancedLabFrame.tsx';
import { privateMcpPractice, privateMcpTool, privateMcpImage, verifyPrivateMcp } from './lab36Mcp.ts';
import { useCourseJob, LiveJobControls } from './useCourseJob.tsx';
export default function Lab36({ active }: { active: boolean }) {
  const state = useCourseJob(36, active); const [origin, setOrigin] = useState<'environment' | 'service'>('environment'); const [selected, setSelected] = useState('success'); const evidence = selected === 'live' && state.job ? state.job : privateMcpPractice(selected);
  return <AdvancedLabFrame lab={36} active={active} title="Run an environment-origin MCP server" intro="Reach a private tool from inside the executor and verify its returned inventory with a fresh marker." evidence={evidence} question="Why can the environment reach this endpoint while service-origin cannot? Which event proves the MCP tool ran?">
    <section className="lab7-card"><h2>Place the tool inside the environment</h2><p>The inventory MCP server binds to 127.0.0.1:8765 inside the disposable container. No Docker port is published. This address belongs to the executor, not the application server or OpenAI service. The endpoint serves only a fixed read-only inventory tool.</p><pre className="lab32-code">{JSON.stringify(privateMcpTool(origin), null, 2)}</pre><p>Lab 24 exposed a server endpoint through a tunnel. Here the connection originates in the environment; no tunnel is used. These synthetic records require no authentication. Private production tools need their own authentication and network controls.</p></section>
    <section className="lab7-card"><h2>Optional live private-tool run</h2><ol><li>Start Docker Desktop in Linux container mode.</li><li><pre className="lab32-code">docker build -t {privateMcpImage} sandbox/lab36</pre></li><li>Configure both distinct keys and LAB36_ENABLE_LOCAL_EXECUTOR=true in .env; restart the server.</li><li>The restricted key needs environment-connection permission and must match the session owner/project. Pin CODEX_VERSION for recordings.</li></ol><label htmlFor="lab36-origin">Connection origin for the next run</label><select id="lab36-origin" value={origin} disabled={state.running || state.busy} onChange={event => setOrigin(event.target.value as typeof origin)}><option value="environment">Environment: executor-local connection</option><option value="service">Service: expected private-endpoint failure</option></select><LiveJobControls state={state} start={() => { void state.start({ origin }).then(ok => { if (ok) setSelected('live'); }); }} /><p className="lab8-note">The container has bounded temporary mounts, a read-only root and no host mounts. The executor can read its restricted connection key. Live outbound networking is available. Runs have a five-minute deadline and two-minute connection wait.</p></section>
    <section className="lab7-card"><h2>Verify a call, not a plausible answer</h2><label htmlFor="lab36-case">Evidence</label><select id="lab36-case" value={selected} onChange={event => setSelected(event.target.value)}><option value="success">Synthetic: successful private MCP call</option><option value="service">Synthetic: wrong connection origin</option><option value="claim">Synthetic: answer without a tool call</option><option value="stale">Synthetic: stale tool marker</option>{state.job ? <option value="live">Current live run</option> : null}</select><p>Source: {evidence.source || evidence.trace.source} | Origin: {evidence.origin}</p><h3>Captured MCP items</h3><pre className="lab32-code">{JSON.stringify(evidence.mcpCalls, null, 2)}</pre><h3>Root answer</h3><pre className="lab32-code">{evidence.trace.answer || 'No final answer observed'}</pre><Checks checks={verifyPrivateMcp(evidence)} /><details><summary>Lifecycle evidence</summary><pre className="lab32-code">{JSON.stringify(evidence.trace, null, 2)}</pre></details><p>Correct inventory text alone does not prove MCP use. A service-origin failure is expected; its evidence checks remain unverified.</p></section>
  </AdvancedLabFrame>;
}
