export const harnessLessons = [
  { number: '01', title: 'Separate the harness from compute', file: 'src/lab31Harness.ts', code: "// Excerpt from architectureEdges(environment)\nif (environment !== 'none') {\n  edges.push({ from: 'harness', to: 'sandbox',\n    label: 'Commands / output / workspace files' });\n}\nif (environment === 'self_hosted') {\n  edges.push({ from: 'server', to: 'sandbox',\n    label: 'Provision / connect executor / reconnect / shutdown' });\n}\nreturn edges;",
    explanation: 'The model generates text and proposes actions. The managed harness runs the repeated model and tool loop and maintains the session. An environment supplies commands and files. Your application connects these pieces to the product. Change the environment selector and inspect the arrows: removing compute does not remove the managed harness, while self hosted compute adds lifecycle responsibilities to your application.' },
  { number: '02', title: 'Compare runtime ownership', file: 'src/lab31Harness.ts', code: "// Selected fields from runtimeComparison\nconst comparison = [\n  { name: 'Agents API',\n    loop: 'OpenAI-managed Codex harness',\n    state: 'Saved session configuration, turns, and items' },\n  { name: 'Agents SDK',\n    loop: 'SDK runner inside your application',\n    state: 'Your storage / SDK sessions or Responses state' },\n  { name: 'Responses API',\n    loop: 'Your integration, with optional hosted orchestration',\n    state: 'Manual history, response chaining, or Conversations' },\n];",
    explanation: 'These are different integration boundaries. The Agents API maintains managed sessions. The Agents SDK runner executes in your application, where you choose deployment and persistence. The Responses API supports model calls, hosted tools, and conversation strategies, while your integration supplies the surrounding workflow. A hosted tool does not mean every tool or business decision is managed. An evaluation runner is a separate program that measures behavior; it is not the execution harness.' },
  { number: '03', title: 'Inspect saved state without starting work', file: 'server/lab31Service.ts', code: "// Excerpt from inspectHarness(api, id)\nif (!validSessionId(id)) throw new Error('Invalid session ID.');\nconst session = object(await api.retrieve(id));\nif (session.id !== id)\n  throw new Error('The API returned a different session.');\nconst [turns, items] = await Promise.all([\n  readPages(after => api.turns(id, after)),\n  readPages(after => api.items(id, after)),\n]);\n// Read-only adapter; partial inventories remain labelled.",
    explanation: 'Reuse a session from an earlier lab and retrieve its saved state through the course server. Reading does not start another turn or create a sandbox. Follow pagination with a bound and label omitted data. Saved items establish the recorded calls and outcomes, but they do not reconstruct exact event timing or expose internal model invocations. The server sends selected public metadata rather than raw agent settings or tool arguments.' },
  { number: '04', title: 'Annotate tool proposals and execution', file: 'src/lab31Harness.ts', code: "// Shortened ownership branches from classifyStep\nswitch (step.kind) {\n  case 'function_call':\n    return { owner: 'model', explanation: 'Proposed action.' };\n  case 'function_result':\n    return { owner: 'server', explanation: 'Handler result.' };\n  case 'command':\n    return { owner: 'sandbox', explanation: 'Command execution.' };\n  case 'mcp_call':\n    return { owner: 'mcp', explanation: 'Remote tool implementation.' };\n  default:\n    return { owner: 'unknown', explanation: 'Review the evidence.' };\n}\n// The full classifier also covers messages and lifecycle steps.",
    explanation: 'A proposed function and its result have different owners. The model requests the function, and your handler validates and executes it. A command runs in the sandbox; an MCP service implements its remote tool. The managed harness coordinates these interactions. Classifying a saved proposal as model work is an architectural inference, not an exposed internal model event. A function result alone does not prove human approval, so inspect the originating lab audit for that claim.' },
  { number: '05', title: 'Use the root turn outcome as evidence', file: 'src/lab31Harness.ts', code: "export function traceOutcome(steps: TraceStep[]): string {\n  const latest = [...steps].reverse().find(\n    step => step.kind === 'turn' && step.root,\n  );\n  return latest && [\n    'completed', 'failed', 'cancelled',\n    'waiting', 'in_progress', 'queued',\n  ].includes(latest.status ?? '')\n    ? latest.status! : 'unknown';\n}\n// Child completion and session idle cannot replace root evidence.",
    explanation: 'The most recent observed root turn determines this view’s outcome. A completed child turn cannot finish the parent task. Session idle is a lifecycle observation, and a closed reader leaves remote work uncertain. A failed sandbox setup may happen before any root turn exists. Step through the disconnect and provisioning examples to see why the page preserves unknown and in progress instead of inventing success.' },
  { number: '06', title: 'Export evidence and narrate the explanation', file: 'src/Lab31.tsx', code: "const markdown = evidenceDocument(trace, notes);\nconst utterance = new SpeechSynthesisUtterance(lesson.explanation);\nconst voice = selectNarratorVoice(voices);\nif (voice) utterance.voice = voice;\nutterance.lang = voice?.lang || 'en-US';\nutterance.rate = 0.95;\nwindow.speechSynthesis.speak(utterance);\n// In the separate Stop handler:\nfunction stopSpeech() {\n  speechRun.current++; // Ignore callbacks from the old queue.\n  window.speechSynthesis.cancel();\n  utterances.current = [];\n  setSpeaking(null);\n}\n// Also stop on collapse, lab change, and unmount.",
    explanation: 'Export the annotated architecture and trace together with your explanation of each boundary. Synthetic practice and imported files keep their source labels and cannot claim a verified live read. Viva voice uses browser speech synthesis with an installed English voice. Each teaching card can read aloud, and Read all six queues the explanations. Stop cancels playback, and narration also stops when the section closes or you leave the lab. Unsupported browsers show an explanation instead of a broken control.' },
];
