import { useEffect, useRef, useState } from 'react';
import Prism from 'prismjs';
import 'prismjs/components/prism-typescript';
import { codeTokens } from './Lab22.tsx';
import { selectNarratorVoice } from './speech.ts';
import { accessPolicy, accessCases, accessPractice, observedProbe, verifyAccess, filesystemImage, type AccessTask } from './lab35Filesystem.ts';
import { runAccessSuite } from './lab35Tests.ts';
import { accessLessons } from './lab35Lessons.ts';
import type { AccessJob } from '../server/lab35.ts';
const saved = (key: string) => { try { return localStorage.getItem(key) || ''; } catch { return ''; } };
const save = (key: string, value: string) => { try { localStorage.setItem(key, value); } catch { /* Current view still works. */ } };
function download(text: string, filename: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([text], { type })); const link = document.createElement('a'); link.href = url; link.download = filename; document.body.append(link); link.click(); link.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
async function json(url: string, body?: unknown, signal?: AbortSignal) { const response = await fetch(url, { ...(body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : {}), signal }); const value = await response.json(); if (!response.ok) throw new Error(value.error || 'Request failed.'); return value; }
export default function Lab35({ active }: { active: boolean }) {
  const [source, setSource] = useState('');
  const [task, setTask] = useState<AccessTask>('standard');
  const [config, setConfig] = useState<{ enabled: boolean; applicationKey: boolean; executorKey: boolean; model: string } | null>(null); const [setup, setSetup] = useState(0); const [checking, setChecking] = useState(false);
  const [job, setJob] = useState<AccessJob | null>(null); const [jobId, setJobId] = useState(() => saved('lab35-job')); const [selected, setSelected] = useState<string>('enforced');
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notes, setNotes] = useState(''); const [tests, setTests] = useState<ReturnType<typeof runAccessSuite> | null>(null); const [testSource, setTestSource] = useState('');
  const [speaking, setSpeaking] = useState<string | null>(null); const speechRun = useRef(0); const utterances = useRef<SpeechSynthesisUtterance[]>([]);
  const speechAvailable = typeof window !== 'undefined' && 'speechSynthesis' in window && typeof SpeechSynthesisUtterance !== 'undefined';
  function stopSpeech() { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); utterances.current = []; setSpeaking(null); }
  useEffect(() => { if (!active) stopSpeech(); }, [active]);
  useEffect(() => () => { speechRun.current++; if (speechAvailable) window.speechSynthesis.cancel(); }, []);
  useEffect(() => {
    if (!active) return; const controller = new AbortController(); setChecking(true);
    void Promise.all([json('/api/lab35/status', undefined, controller.signal), json('/api/lab35/probe', undefined, controller.signal)])
      .then(([status, bundle]) => { if (controller.signal.aborted) return; setConfig(status); setSource(bundle.source); setError(''); })
      .catch(failure => { if (!controller.signal.aborted) { setConfig(null); setError(failure.message); } }).finally(() => { if (!controller.signal.aborted) setChecking(false); });
    return () => controller.abort();
  }, [active, setup]);
  useEffect(() => {
    if (!active || !jobId) return; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>;
    async function poll() { try { const data = await json(`/api/lab35/job?id=${encodeURIComponent(jobId)}`, undefined, controller.signal); if (controller.signal.aborted) return; setJob(data.job); if (data.job.status === 'running') timer = setTimeout(poll, 1000); } catch (failure) { if (!controller.signal.aborted) { setError(`${failure.message} If the server restarted, check the named Docker container and saved API session.`); timer = setTimeout(poll, 5000); } } }
    void poll(); return () => { controller.abort(); clearTimeout(timer); };
  }, [active, jobId]);
  function speak(queue: typeof accessLessons, all = false) {
    const marker = all ? 'all' : queue[0].number; if (speaking === marker) { stopSpeech(); return; } stopSpeech(); if (!speechAvailable) return;
    const run = speechRun.current; const voice = selectNarratorVoice(window.speechSynthesis.getVoices());
    utterances.current = queue.map((lesson, index) => { const utterance = new SpeechSynthesisUtterance(`${lesson.title}. ${lesson.explanation}`); if (voice) utterance.voice = voice; utterance.lang = voice?.lang || 'en-US'; utterance.rate = .95; utterance.onend = () => { if (run === speechRun.current && index === queue.length - 1) setSpeaking(null); }; utterance.onerror = () => { if (run === speechRun.current) { stopSpeech(); setError('Narration could not play. Try an installed English voice.'); } }; return utterance; }); setSpeaking(marker); utterances.current.forEach(utterance => window.speechSynthesis.speak(utterance));
  }
  async function start() { setBusy(true); setError(''); const requestId = saved('lab35-request') || crypto.randomUUID(); save('lab35-request', requestId);
    try { const data = await json('/api/lab35/run', { requestId, task }); setJob(data.job); setJobId(data.job.id); save('lab35-job', data.job.id); save('lab35-request', ''); setSelected('live'); } catch (failure) { setError(`${failure.message} Retry keeps the same request ID to avoid duplicate compute.`); } finally { setBusy(false); }
  }
  async function control(action: 'stop' | 'cleanup') { if (!job) return; setBusy(true); setError(''); try { setJob((await json(`/api/lab35/${action}`, { id: job.id })).job); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  async function serverTests() { try { setTests((await json('/api/lab35/test', {})).results); setTestSource('server'); } catch (failure) { setError(failure.message); } }
  const live = selected === 'live' && Boolean(job); const trace = live ? job!.trace : accessPractice(selected); const observed = observedProbe(trace); const checks = verifyAccess(trace); const running = job?.status === 'running'; const cleanupFailed = job?.trace.cleanup === 'failed' || job?.sessionCleanup === 'failed';
  const blockers = [...(!config ? ['Server setup is not available. Use localhost and recheck setup.'] : [...(!config.enabled ? ['Set LAB35_ENABLE_LOCAL_EXECUTOR=true in .env.'] : []), ...(!config.applicationKey ? ['Configure OPENAI_API_KEY in .env.'] : []), ...(!config.executorKey ? ['Configure a distinct restricted OPENAI_EXECUTOR_API_KEY in .env.'] : [])]), ...(running ? ['Wait for the current run or stop it.'] : []), ...(cleanupFailed ? ['Retry cleanup before starting another run.'] : [])];
  return <div className="lab16-page lab31-page lab32-page lab35-page">
    <section className="lab-hero"><span className="eyebrow">LAB 35 / FILESYSTEM ACCESS</span><h1>Limit filesystem access</h1><p>Give the agent a task workspace and enforce protected paths with operating-system permissions.</p><div className="lab26-hero-badges"><span>Unprivileged executor</span><span>Protected fixtures</span><span>Observed access results</span></div></section>
    <section className="lab7-card"><span className="eyebrow">ACCESS POLICY / NO KEY REQUIRED</span><h2>Predict access before running commands</h2><p>The Docker image runs as UID 1000. Root owns the protected directory (0700) and file (0600). The root filesystem is read-only; /workspace, /tmp and the executor home have bounded writable mounts. No host directory is mounted.</p><table className="lab33-comparison"><thead><tr><th>Operation and path</th><th>Expected</th><th>Enforcement</th></tr></thead><tbody>{accessPolicy.map(row => <tr key={row.id}><td>{row.operation} <code>{row.path}</code></td><td>{row.expected}</td><td>{row.reason}</td></tr>)}</tbody></table><p>Readable runtime files outside /workspace remain available. This lab enforces specific protected paths; workspace_directory and prompt instructions alone do not enforce a filesystem boundary. The executor can read its restricted connection key.</p><details><summary>Inspect the fixed probe</summary><pre className="lab32-code">{source || 'Loading probe...'}</pre></details></section>
    <section className="lab7-card"><span className="eyebrow">OPTIONAL LIVE SELF-HOSTED RUN</span><h2>Try a broader request against the enforced boundary</h2><details open={Boolean(config && blockers.length)}><summary>Setup before the first live run</summary><ol><li>Run Docker Desktop in Linux container mode.</li><li>Build the image: <pre className="lab32-code">docker build -t {filesystemImage} sandbox/lab35</pre></li><li>Configure OPENAI_API_KEY, a distinct restricted OPENAI_EXECUTOR_API_KEY, and LAB35_ENABLE_LOCAL_EXECUTOR=true in .env. Restart the course server.</li><li>The restricted key must share the session’s organization, project and owner, and have only environment-connection permissions. Pin CODEX_VERSION to a verified exact CLI version for reproducible recordings.</li></ol></details><div className="lab31-facts"><span><strong>Local executor</strong>{config?.enabled ? 'Enabled' : 'Disabled'}</span><span><strong>Application key</strong>{config?.applicationKey ? 'Configured' : 'Not configured'}</span><span><strong>Restricted key</strong>{config?.executorKey ? 'Configured' : 'Not configured'}</span><span><strong>Model</strong>{config?.model || 'Checking…'}</span></div>
      <label htmlFor="lab35-task">Task</label><select id="lab35-task" value={task} disabled={running || busy} onChange={event => setTask(event.target.value as AccessTask)}><option value="standard">Verify workspace and protected paths</option><option value="broader">Explicitly request protected access, traversal and symlink</option></select><div id="lab35-blockers" aria-live="polite">{blockers.length ? <ul>{blockers.map(reason => <li key={reason}>{reason}</li>)}</ul> : null}</div><div className="lab30-toolbar"><button type="button" className="lab8-secondary" disabled={checking} onClick={() => setSetup(value => value + 1)}>{checking ? 'Checking…' : 'Recheck setup'}</button><button type="button" className="lab8-run" disabled={Boolean(blockers.length) || busy || checking} aria-describedby="lab35-blockers" onClick={start}>{running ? 'Run in progress…' : 'Connect and run task'}</button><button type="button" className="lab8-secondary" disabled={!running || busy} onClick={() => control('stop')}>Stop run and clean up</button><button type="button" className="lab8-secondary" disabled={!cleanupFailed || running || busy} onClick={() => control('cleanup')}>Retry cleanup</button></div><p className="lab8-note">Each run creates an API session and a fresh Docker container with bounded temporary storage. No host project or Docker socket is mounted. Outbound networking is available. The executor can read its restricted key. The job has a five-minute deadline and a two-minute connection wait. Browser navigation leaves the server job running; reopening resumes polling its saved ID.</p>{job ? <p>Run: <code>{job.id}</code> · {job.status} · Container: <code>{job.containerName}</code> · API cleanup: {job.sessionCleanup}</p> : null}{error ? <p role="alert" className="lab31-error">{error}</p> : null}</section>
    <section className="lab7-card"><span className="eyebrow">PRACTICE AND OBSERVED EVIDENCE</span><h2>A permission failure needs command evidence</h2><label htmlFor="lab35-case">Evidence case</label><select id="lab35-case" value={selected} onChange={event => setSelected(event.target.value)}>{accessCases.map(row => <option key={row.id} value={row.id}>{row.title}</option>)}{job ? <option value="live">Current live run</option> : null}</select><p>{live ? 'Actual server-run evidence.' : 'Synthetic practice only; these are teaching fixtures, not recorded model output.'}</p><p>Connection: {trace.connection} | Root: {trace.outcome} | Cleanup: {trace.cleanup}</p>{trace.error ? <p className="lab31-error">{trace.error}</p> : null}<table className="lab33-comparison"><thead><tr><th>Probe</th><th>Observed</th><th>OS result</th></tr></thead><tbody>{accessPolicy.map(policy => { const row = observed?.tests.find(row => row.id === policy.id); return <tr key={policy.id}><td>{policy.id}</td><td>{row?.actual || 'Not observed'}</td><td>{row?.code ?? (row ? 'Success' : 'Unknown')}</td></tr>; })}</tbody></table><p>EACCES, EPERM and EROFS establish denied access for these fixtures. ENOENT means a missing file and does not establish permission enforcement. A refusal in the final answer alone does not establish denial.</p><details><summary>Lifecycle events</summary><ol className="lab32-events">{trace.events.map((event, index) => <li key={index}><code>{event.name}</code><span>{event.ms} ms</span></li>)}</ol></details><h3>Completed commands</h3>{trace.commands.length ? trace.commands.map(command => <div key={command.id}><p>Exit: {command.exitCode ?? 'unknown'}</p><pre className="lab32-code">{command.command}{'\n\n'}{command.output}</pre></div>) : <p>No completed commands observed.</p>}<h3>Final answer</h3><pre className="lab32-code">{trace.answer || 'No final answer observed.'}</pre><ul className="lab32-checks">{checks.map(check => <li key={check.name} className={check.passed ? 'lab29-ok' : 'lab31-error'}>{check.passed ? 'PASS' : 'NOT VERIFIED'} | {check.name}</li>)}</ul><p className="lab8-note">The checker validates captured fixture evidence and consistency. It does not prove that an adversarial executor cannot fabricate output, or that every outside path is inaccessible. Inspect the image permissions and Docker controls independently.</p></section>
    <section className="lab7-card"><span className="eyebrow">STUDENT EVIDENCE</span><h2>Explain which layer enforced each result</h2><label htmlFor="lab35-notes">Compare the standard and broader requests. Why do traversal and symlink attempts fail? Which outside path remains readable?</label><textarea id="lab35-notes" rows={5} maxLength={5000} value={notes} onChange={event => setNotes(event.target.value)} /><button type="button" className="lab8-secondary" onClick={() => download(JSON.stringify({ trace, checks, notes }, null, 2), 'lab35-filesystem-evidence.json', 'application/json')}>Export evidence</button><p>Challenge: capture both live tasks, explain each allowed or denied operation, and distinguish a model refusal, a missing fixture and a kernel permission failure.</p></section>
    <section className="lab7-card"><span className="eyebrow">SHARED TEST PAGE / NO KEY REQUIRED</span><h2>Check access and evidence rules</h2><div className="lab30-toolbar"><button type="button" className="lab8-secondary" onClick={() => { setTests(runAccessSuite()); setTestSource('browser'); }}>Run browser tests</button><button type="button" className="lab8-secondary" onClick={serverTests}>Run server tests</button></div>{tests ? <><p role="status">{tests.filter(row => row.passed).length} / {tests.length} passed · {testSource}</p><ul className="lab30-test-list">{tests.map(row => <li key={row.name}>{row.passed ? 'PASS' : 'FAIL'} · {row.name}</li>)}</ul></> : null}</section>
    <details className="code-lessons lab5-code" onToggle={event => { if (!event.currentTarget.open) stopSpeech(); }}><summary className="code-lessons-toggle"><span className="code-lessons-heading"><span className="code-lessons-kicker">UNDER THE HOOD · LAB 35</span><span className="code-lessons-title" role="heading" aria-level={2}>How the filesystem lab was built</span><span className="code-lessons-hint">Six explained snippets with Viva voice narration.</span></span><span className="code-lessons-toggle-action">View code</span></summary><div className="code-lessons-body"><div className="lab30-toolbar"><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === 'all'} onClick={() => speak(accessLessons, true)}>Viva voice · Read all six</button><button type="button" className="lab8-secondary" disabled={!speaking} onClick={stopSpeech}>Stop narration</button></div><div className="code-lessons-grid">{accessLessons.map(lesson => <article className="code-lesson" key={lesson.number}><div className="code-lesson-header"><span className="code-lesson-number">{lesson.number}</span><div><h3>{lesson.title}</h3><span>{lesson.file}</span></div></div><pre><code>{codeTokens(Prism.tokenize(lesson.code, Prism.languages.typescript || Prism.languages.javascript))}</code></pre><p>{lesson.explanation}</p><button type="button" className="viva-button" disabled={!speechAvailable} aria-pressed={speaking === lesson.number} onClick={() => speak([lesson])}>Viva voice · Read aloud</button></article>)}</div></div></details>
    <section className="lab7-card"><span className="eyebrow">OFFICIAL REFERENCES / CHECKED 2026-10-05</span><h2>Sandbox security and executor isolation</h2><ul><li><a href="https://developers.openai.com/api/docs/guides/agents-api/environments/security" target="_blank" rel="noopener noreferrer">Environment security</a></li><li><a href="https://developers.openai.com/api/docs/guides/agents-api/environments/self-hosted" target="_blank" rel="noopener noreferrer">Self-hosted environments</a></li></ul></section>
  </div>;
}
