import { useState } from 'react';
import { AdvancedLabFrame, Checks } from './AdvancedLabFrame.tsx';
import { recoveryCases, recoveryDecision, recoveryPractice, verifyRecovery } from './lab37Recovery.ts';
import { useCourseJob, LiveJobControls } from './useCourseJob.tsx';
export default function Lab37({ active }: { active: boolean }) {
  const state = useCourseJob(37, active); const [selected, setSelected] = useState('stream'); const [answer, setAnswer] = useState(''); const [fault, setFault] = useState('stream'); const scenario = recoveryCases.find(row => row.id === selected) ?? recoveryCases[0]; const evidence = selected === 'live' && state.job ? state.job.recovery : recoveryPractice(selected);
  return <AdvancedLabFrame lab={37} active={active} title="Recover an environment failure" intro="Inspect saved state, reconnect only when justified, and preserve input identity across observation loss." evidence={state.job && selected === 'live' ? state.job : evidence} question="Distinguish stream loss, executor loss and setup failure. What survives reconnection, and why must input not be blindly resubmitted?">
    <section className="lab7-card"><h2>Choose a recovery from saved state</h2><label htmlFor="lab37-case">Failure case</label><select id="lab37-case" value={selected} onChange={event => { setSelected(event.target.value); setAnswer(''); }}>{recoveryCases.map(row => <option key={row.id} value={row.id}>Synthetic: {row.title}</option>)}{state.job ? <option value="live">Current live run</option> : null}</select>{selected !== 'live' ? <><p>Environment: {scenario.status} | Root: {scenario.outcome} | Recovery attempts used: {scenario.attempts}</p><label htmlFor="lab37-decision">Your next action</label><select id="lab37-decision" value={answer} onChange={event => setAnswer(event.target.value)}><option value="">Choose an action</option>{['inspect-result', 'new-run', 'stop-and-cleanup', 'reconnect-environment', 'reattach-stream', 'inspect-state'].map(value => <option key={value}>{value}</option>)}</select>{answer ? <p role="status">{answer === recoveryDecision(scenario.status, scenario.outcome, scenario.attempts) ? 'Correct: preserve the session and input mapping where recovery remains possible.' : 'Recheck the terminal outcome, environment status and one-attempt budget.'}</p> : null}</> : null}<pre className="lab32-code">{JSON.stringify(evidence, null, 2)}</pre><Checks checks={verifyRecovery(evidence)} /><p>Practice cases are synthetic. Expired or failed environments require a corrected new run, not an invented success. A completed saved root needs inspection, not another input submission.</p></section>
    <section className="lab7-card"><h2>Optional live stream-loss exercise</h2><p>Build the Lab 32 image: <code>docker build -t agents-lab32-executor:local sandbox/lab32</code>. Configure both keys and LAB37_ENABLE_LOCAL_EXECUTOR=true, then restart. The task is a read-only fixture listing. A five-minute deadline bounds the run.</p><label htmlFor="lab37-fault">Observation fault</label><select id="lab37-fault" disabled={state.running || state.busy} value={fault} onChange={event => setFault(event.target.value)}><option value="stream">Close one local subscription after input acceptance</option><option value="none">No injected fault</option></select><LiveJobControls state={state} start={() => { void state.start({ fault }).then(ok => { if (ok) setSelected('live'); }); }} /><p>The injected fault closes only the application's subscription; it does not simulate an executor crash. The worker retrieves saved session, environment, turns and items, then inspects a terminal result or reattaches once. A real disconnected executor is replaced only after validating its mapping. The replacement rebuilds deterministic fixture inputs; volatile filesystem changes are not preserved. The same session and original submission continue only if the remote turn remains resumable. After settlement, compute and session are cleaned up independently.</p></section>
  </AdvancedLabFrame>;
}
