type Lesson = { title: string; file: string; code: string; explanation: string };
const rules = 'src/operationsLabRules.ts', ui = 'src/OperationsLab.tsx', service = 'server/operationsService.ts', routes = 'server/labs41to50.ts';
const entries: Record<number, Array<[string, string, string, string]>> = {
  41: [
    ['Track ownership', rules, 'turn.subagent_id ?? null', 'Turn resources identify their child owner. A null owner identifies the root.'],
    ['Replay events incrementally', rules, 'events.slice(0, count).forEach((event, i) => applyDelegationEvent(trace, event, i * 100));', 'Step through a labelled synthetic sequence to see status changes before the root settles.'],
    ['Child success', rules, "replayProgress(progressEvents(), 6).root === 'unknown'", 'Completing the writer child leaves the coordinator pending.'],
    ['Child failure', rules, "progressDecision(replayProgress(progressEvents(true), 7))", 'A failed child prompts bounded recovery or saved-state inspection while the root continues.'],
    ['Root outcome', rules, "if (trace.root === 'completed') return 'Inspect root answer and completeness';", 'A completed root still needs its answer checked for missing work.'],
    ['Export evidence', ui, 'evidence = trace', 'Export turn ownership, events and notes; compare with the live event evidence available in Lab 40.'],
  ],
  42: [
    ['Ground the task', rules, 'reviewSource', 'One fixed source describes the search and export changes and permitted contact.'],
    ['Separate roles', ui, 'setReviewedDraft(draft); setReview(reviewDraft(draft));', 'The reviewer returns findings against a snapshot rather than editing the writer output.'],
    ['Acceptance IDs', rules, "{ id: 'AC-02', name: 'Export change and migration action' }", 'Each finding identifies the criterion the writer must resolve.'],
    ['Find a regression', rules, "!/returns file bytes|no client changes/i.test(draft)", 'The exercise catches the known incompatible claim in the flawed draft.'],
    ['Return revisions', ui, 'setDraft(revisedFixture)', 'The writer applies the example revision; students can edit their own draft in the same field.'],
    ['Re-review changed work', ui, 'draft !== reviewedDraft', 'A report becomes stale when the draft changes. Review again before accepting the new output.'],
  ],
  43: [
    ['Match task and model', rules, 'single.task === reviewSource && multi.model === single.model', 'Reject comparisons with different sources or model settings.'],
    ['Shared quality checks', rules, 'reviewDraft(row.draft).filter(check => check.passed).length', 'Both modes use the same acceptance criteria instead of subjective labels.'],
    ['Duration', rules, 'durationMs: number | null', 'Elapsed wall time may be unknown; parallel child durations must not simply be added.'],
    ['Coordination cost', rules, 'coordinationCalls: number; recoveryAttempts: number', 'Compare orchestration overhead and recovery attempts along with successful output.'],
    ['Nullable tokens', rules, 'usage: usageSummary(row.turns)', 'Incomplete turn accounting cannot support a precise token-cost conclusion.'],
    ['Recommend from evidence', rules, 'rows[1].quality > rows[0].quality', 'A quality gain can justify delegation in this task, but repeated matched runs are needed for a broader recommendation.'],
  ],
  44: [
    ['Preserve raw body', routes, "for await (const chunk of request) raw += chunk", 'Verify the exact received payload, bounded to sixteen kilobytes, before parsing.'],
    ['Official verifier', service, 'await verifier.webhooks.verifySignature(raw, headers);', 'Use the installed SDK to enforce signature and timestamp validation.'],
    ['Supported notifications', rules, "'agent.session.idle', 'agent.session.failed'", 'Session webhook event types differ from turn lifecycle events on the stream.'],
    ['Persist before acknowledging', service, "await appendFile(this.file, JSON.stringify(event) + '\\n')", 'A successful response follows the durable append; retries can then deduplicate the event.'],
    ['Serialize replay checks', service, 'const write = this.pending.then(async () => { /* check and append */ });', 'A process-local queue keeps concurrent deliveries from appending the same event twice.'],
    ['Inspect outcome', service, "outcome: 'Inspect turn; idle is not proof of success'", 'A notification is evidence of delivery. Retrieve current session and turn state before consequential work.'],
  ],
  45: [
    ['Choose supported event', rules, 'hooks: { PostToolUse: [...] }', 'This configuration targets Codex lifecycle dispatch, not the Agents API session schema.'],
    ['Bound matching', rules, "matcher: '^(apply_patch|Edit|Write)$'", 'Only file edits match; shell commands do not recursively trigger validation.'],
    ['Bound command time', rules, 'timeout: 10', 'Codex timeout is in seconds. The application callback independently limits the same command.'],
    ['Project and plugin paths', rules, 'node "${PLUGIN_ROOT}/validate-report.mjs"', 'The plugin command uses its installed root; the project command uses the exercise working directory.'],
    ['Command feedback', 'sandbox/lab45/validate-report.mjs', "process.exitCode = passed ? 0 : 2", 'A failed post-tool command reports validation failure but cannot undo the edit that already ran.'],
    ['Runtime trust evidence', ui, '/hooks', 'Inspect and trust the exact configuration in a supported Codex runtime. Direct command validation does not prove lifecycle dispatch.'],
  ],
  46: [
    ['Detect page API', ui, '(document as any).modelContext', 'Use the interface currently documented for ChatGPT site tools, and handle unavailable browser support.'],
    ['Register narrow tools', ui, "name: 'lab46_read_report'", 'The read tool returns only the displayed course report and current filter.'],
    ['Validate arguments', rules, "validateToolInput(args, ['filter'])", 'Reject extra fields before passing the filter to existing application logic.'],
    ['Update React state', ui, 'page.current.filter = next; setFilter(next);', 'A reference keeps tool reads current between React renders and the visible state changes with the same operation.'],
    ['Record invocation source', ui, "invoke(name, args, 'Native WebMCP execute')", 'Native callbacks and local demo buttons are logged separately to avoid inventing browser evidence.'],
    ['Remove page tools', ui, 'context.unregisterTool(name)', 'Leaving this lab removes its tools; asynchronous registration is also cleaned up when it finishes late.'],
  ],
  47: [
    ['Import supported export', rules, 'value.resourceSpans ?? value.data?.flatMap(row => row.otlp?.resourceSpans || [])', 'Accept OTLP payloads or the documented trace export page envelope.'],
    ['Flatten span groups', rules, 'resource.scopeSpans.flatMap(scope => scope.spans)', 'The table lists all imported spans rather than only the first scope.'],
    ['Retain hierarchy', rules, "parent: span.parentSpanId || ''", 'Parent IDs connect tools to generations and turns; missing parents may be outside a partial page.'],
    ['Read status honestly', rules, "span.status?.code === 2 ? 'error' : span.status?.code === 1 ? 'ok' : 'unset'", 'An unset OTLP status does not prove success.'],
    ['Inspect details', ui, 'spans.find(span => span.id === selectedSpan)', 'Select individual spans to inspect recorded attributes and timestamps.'],
    ['Bound imports', rules, 'spans.length > 500', 'Reject oversized and duplicate span sets; paginate full exports outside this teaching inspector.'],
  ],
  48: [
    ['Nullable resource', rules, 'usage: TokenCounts | null', 'The API can report unknown usage; the dashboard preserves that absence.'],
    ['Validate counts', rules, 'Number.isSafeInteger(row.usage[key]) && row.usage[key] >= 0', 'Reject negative or malformed counts before aggregation.'],
    ['Replace snapshots', rules, 'rows.set(row.id, row)', 'Later observations of one turn replace earlier counts instead of double counting.'],
    ['Separate subtotal', rules, 'known.reduce((sum, row) => sum + row.usage.total_tokens, 0)', 'Show known work alongside the number of unknown turns.'],
    ['Unknown total', rules, 'rows.length === known.length ? knownSubtotal : null', 'A partial subtotal is not an exact total. An empty inventory also remains unknown.'],
    ['Avoid a fake bill', ui, "summary.total ?? 'Unknown'", 'Best-effort tokens are not final billing; cached and reasoning categories are subsets, not additional totals.'],
  ],
  49: [
    ['Reserve first', routes, 'const budget = ownership.reserve(principal);', 'The application rejects exhausted identities before retry work begins.'],
    ['Safe reads only', rules, 'if (!safe) return null;', 'An uncertain write is not automatically resubmitted by this retry policy.'],
    ['Transient status list', rules, '[408, 429, 500, 502, 503, 504]', 'Authentication and validation errors stop immediately.'],
    ['Respect Retry-After', rules, 'if (header > 5000) return null;', 'A provider wait longer than the bounded request ends the attempt instead of retrying too early.'],
    ['Four attempts maximum', service, 'for (let index = 0; index < 4; index++)', 'Attempt count and delays are recorded for inspection, including exhausted failures.'],
    ['Request budget scope', service, 'row.used >= 3', 'Three application requests per minute are allowed per demo identity. This is not a dollar-spend guarantee.'],
  ],
  50: [
    ['Demo sign-in boundary', service, "if (!['alice', 'bob'].includes(user)) throw new Error(...)", 'A local identity selector stands in for validated production credentials and is labelled accordingly.'],
    ['Opaque cookie', service, "randomBytes(32).toString('hex')", 'The browser holds an unpredictable server-issued token, not a client-selected owner assertion.'],
    ['Authenticate before access', routes, 'const principal = ownership.identity(tokenFrom(request));', 'Expired or missing tokens fail before any session operation.'],
    ['Map application IDs', service, 'sessions.set(id, { owner: user, providerId, status })', 'Clients receive application IDs; provider session IDs remain server-side.'],
    ['Check every operation', service, 'if (!row || !ownsSession(user, row)) return null;', 'Read, stop and delete all enforce the same ownership check and conceal foreign existence.'],
    ['Revoke identity', routes, 'ownership.identities.delete(tokenFrom(request));', 'Logout revokes the server-side token as well as clearing the cookie. Restart also clears this teaching store.'],
  ],
};
export const operationsLessons: Record<number, Lesson[]> = Object.fromEntries(Object.entries(entries).map(([id, rows]) => [id, rows.map(([title, file, code, explanation]) => ({ title, file, code, explanation }))]));
