import { useState } from 'react';
import { pluginAvailability } from './lab25Reinforcement.ts';
import { checkPlugin, type PluginFile } from './lab25Plugin.ts';
import { downloadEvidence } from './AdvancedLabFrame.tsx';
export default function PluginReinforcement({ files }: { files: PluginFile[] }) {
  const [unavailable, setUnavailable] = useState(false);
  const check = checkPlugin(files);
  const valid = Boolean(check.manifest && !check.findings.some(row => row.level === 'error'));
  const result = pluginAvailability(files, { installed: valid ? [{ name: check.manifest!.name, description: check.manifest!.description }] : [], calls: valid ? check.servers.map(server => ({ id: `fixture-${server.label}`, server: server.label, name: 'fixture_lookup', kind: 'tool' as const, status: unavailable ? 'failed' as const : 'completed' as const, turnId: 'fixture', arguments: {}, output: unavailable ? null : 'Documentation result (injected fixture)', error: unavailable ? { code: null, message: 'Injected unavailable MCP' } : null, isError: unavailable })) : [] });
  return <section className="lab7-card"><h2>Compare the skill with an unavailable MCP</h2><p>This injected exercise compares the same installed package with a working tool and a failed tool. The skill text remains available in both; its instruction to retrieve documentation requires a successful MCP result.</p><label><input type="checkbox" checked={unavailable} onChange={event => setUnavailable(event.target.checked)} /> Inject unavailable documentation MCP</label><table><thead><tr><th>Part</th><th>Evidence</th></tr></thead><tbody>{result.skills.map(skill => <tr key={skill.name}><td>Skill: {skill.name}</td><td>{skill.available ? 'Instructions available in installed package' : 'Package not installed'}</td></tr>)}{result.servers.map(server => <tr key={server.label}><td>MCP: {server.label}</td><td>{server.status}</td></tr>)}</tbody></table><p>{unavailable ? 'Follow the skill’s formatting and review rules, disclose the unavailable server, and leave unsupported documentation claims unresolved.' : 'Use returned documentation to ground claims; inspect source links before accepting the answer.'}</p><button className="lab8-secondary" onClick={() => downloadEvidence({ fixture: true, unavailable, ...result }, 'lab25-plugin-availability.json')}>Export comparison evidence</button><p>For a live comparison, set environment.network to disabled in the workbench, create a new session, and compare its MCP errors with the working run. Do not label this injected exercise as a live failure.</p></section>;
}
