import { useEffect, useState } from 'react';
import { labJson, storageGet, storageSet } from './AdvancedLabFrame.tsx';
export function useCourseJob(lab: number, active: boolean) {
  const [config, setConfig] = useState<any>(null); const [job, setJob] = useState<any>(null); const [id, setId] = useState(() => storageGet(`lab${lab}-job`)); const [refresh, setRefresh] = useState(0); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [checking, setChecking] = useState(false);
  useEffect(() => { if (!active) return; const controller = new AbortController(); setChecking(true); void labJson(`/api/lab${lab}/status`, undefined, controller.signal).then(value => { if (!controller.signal.aborted) setConfig(value); }).catch(failure => { if (!controller.signal.aborted) { setConfig(null); setError(failure.message); } }).finally(() => { if (!controller.signal.aborted) setChecking(false); }); return () => controller.abort(); }, [active, lab, refresh]);
  useEffect(() => { if (!active || !id) return; const controller = new AbortController(); let timer: ReturnType<typeof setTimeout>; async function poll() { try { const value = await labJson(`/api/lab${lab}/job?id=${encodeURIComponent(id)}`, undefined, controller.signal); if (controller.signal.aborted) return; setJob(value.job); if (value.job.status === 'running') timer = setTimeout(poll, 1000); } catch (failure) { if (!controller.signal.aborted) setError(`${failure.message} Check exported identifiers after a server restart.`); } } void poll(); return () => { controller.abort(); clearTimeout(timer); }; }, [active, lab, id]);
  async function start(options: Record<string, unknown>) { setBusy(true); setError(''); const requestId = storageGet(`lab${lab}-request`) || crypto.randomUUID(); storageSet(`lab${lab}-request`, requestId); try { const value = await labJson(`/api/lab${lab}/run`, { requestId, ...options }); setJob(value.job); setId(value.job.id); storageSet(`lab${lab}-job`, value.job.id); storageSet(`lab${lab}-request`, ''); return true; } catch (failure) { setError(`${failure.message} Retry retains the request ID to avoid duplicate work.`); return false; } finally { setBusy(false); } }
  async function control(action: 'stop' | 'cleanup') { if (!job) return; setBusy(true); setError(''); try { setJob((await labJson(`/api/lab${lab}/${action}`, { id: job.id })).job); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  const running = job?.status === 'running'; const cleanupFailed = job?.trace?.cleanup === 'failed' || job?.sessionCleanup === 'failed' || job?.recovery?.cleanup === 'failed';
  const blockers = [...(!config ? ['Recheck the localhost server setup.'] : [...(!config.applicationKey ? ['Configure OPENAI_API_KEY and restart the server.'] : []), ...(lab < 38 && !config.enabled ? [`Set LAB${lab}_ENABLE_LOCAL_EXECUTOR=true and restart.`] : []), ...(lab < 38 && !config.executorKey ? ['Configure a distinct restricted OPENAI_EXECUTOR_API_KEY.'] : [])]), ...(running ? ['Wait for the running job or stop it.'] : []), ...(cleanupFailed ? ['Retry cleanup before another run.'] : [])];
  return { config, job, error, busy, checking, running, cleanupFailed, blockers, start, control, recheck: () => setRefresh(value => value + 1) };
}
export function LiveJobControls({ state, start }: { state: ReturnType<typeof useCourseJob>; start: () => void }) {
  return <><div className="lab31-facts"><span><strong>Application key</strong>{state.config?.applicationKey ? 'Configured' : 'Not configured'}</span><span><strong>Model</strong>{state.config?.model || 'Checking...'}</span></div>{state.blockers.length ? <ul>{state.blockers.map(row => <li key={row}>{row}</li>)}</ul> : null}<div className="lab30-toolbar"><button type="button" className="lab8-secondary" disabled={state.checking} onClick={state.recheck}>Recheck setup</button><button type="button" className="lab8-run" disabled={state.busy || state.checking || Boolean(state.blockers.length)} onClick={start}>Run live task</button><button type="button" className="lab8-secondary" disabled={!state.running || state.busy} onClick={() => state.control('stop')}>Stop and clean up</button><button type="button" className="lab8-secondary" disabled={!state.cleanupFailed || state.running || state.busy} onClick={() => state.control('cleanup')}>Retry cleanup</button></div>{state.job ? <p>Run: <code>{state.job.id}</code> | {state.job.status}{state.job.containerName ? <> | Container: <code>{state.job.containerName}</code></> : null} | Session: <code>{state.job.trace?.sessionId || 'not created'}</code></p> : null}{state.error ? <p role="alert" className="lab31-error">{state.error}</p> : null}<p className="lab8-note">Jobs stay on the server when you switch labs. Returning resumes polling the saved ID. A server restart loses this local job inventory; export evidence before restarting. Deadlines and cleanup retries are bounded. This teaching runner accepts same-origin localhost requests.</p></>;
}
